<a href="https://colab.research.google.com/github/dodamhaee/CV-anomaly-detection-algorithm/blob/main/classify_img.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import shutil
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd drive/MyDrive/Dacon

/content/drive/MyDrive/Dacon

In [4]:
df = pd.read_csv('train_df.csv')

In [5]:
df = df[['class', 'file_name']]
df

           class  file_name
0     transistor  10000.png
1        capsule  10001.png
2     transistor  10002.png
3           wood  10003.png
4         bottle  10004.png
...          ...        ...
4272  transistor  14272.png
4273  transistor  14273.png
4274        grid  14274.png
4275      zipper  14275.png
4276       screw  14276.png

[4277 rows x 2 columns]

In [6]:
df = df.sort_values(['class', 'file_name'])
df

       class  file_name
4     bottle  10004.png
26    bottle  10026.png
53    bottle  10053.png
58    bottle  10058.png
60    bottle  10060.png
...      ...        ...
4240  zipper  14240.png
4242  zipper  14242.png
4243  zipper  14243.png
4244  zipper  14244.png
4275  zipper  14275.png

[4277 rows x 2 columns]

### **각 class에 해당하는 file name들의 list 생성**

In [7]:
# class가 bottle인 경우의 file name 추출
bottle = df.loc[df['class'] == 'bottle', ['file_name']]
bottle

      file_name
4     10004.png
26    10026.png
53    10053.png
58    10058.png
60    10060.png
...         ...
4174  14174.png
4179  14179.png
4200  14200.png
4236  14236.png
4271  14271.png

[241 rows x 1 columns]

In [8]:
# bottle의 file name list화
bottle = bottle['file_name'].values
bottle

array(['10004.png', '10026.png', '10053.png', '10058.png', '10060.png',
       '10094.png', '10159.png', '10172.png', '10204.png', '10207.png',
       '10217.png', '10221.png', '10240.png', '10244.png', '10248.png',
       '10257.png', '10260.png', '10262.png', '10308.png', '10355.png',
       '10375.png', '10382.png', '10385.png', '10401.png', '10403.png',
       '10447.png', '10458.png', '10474.png', '10482.png', '10520.png',
       '10524.png', '10542.png', '10552.png', '10566.png', '10569.png',
       '10574.png', '10580.png', '10581.png', '10584.png', '10645.png',
       '10653.png', '10674.png', '10681.png', '10701.png', '10712.png',
       '10744.png', '10751.png', '10759.png', '10767.png', '10772.png',
       '10779.png', '10784.png', '10792.png', '10794.png', '10827.png',
       '10837.png', '10839.png', '10871.png', '10875.png', '10898.png',
       '10912.png', '10913.png', '10916.png', '10938.png', '10968.png',
       '10991.png', '11018.png', '11022.png', '11023.png', '11030.png',
       '11051.png', '11083.png', '11133.png', '11140.png', '11143.png',
       '11170.png', '11252.png', '11273.png', '11295.png', '11307.png',
       '11310.png', '11323.png', '11332.png', '11338.png', '11352.png',
       '11389.png', '11401.png', '11463.png', '11559.png', '11575.png',
       '11628.png', '11629.png', '11642.png', '11647.png', '11649.png',
       '11664.png', '11683.png', '11716.png', '11728.png', '11734.png',
       '11735.png', '11741.png', '11755.png', '11763.png', '11791.png',
       '11796.png', '11799.png', '11804.png', '11805.png', '11815.png',
       '11828.png', '11837.png', '11840.png', '11866.png', '11875.png',
       '11876.png', '11885.png', '11894.png', '11905.png', '11907.png',
       '11912.png', '11949.png', '11961.png', '11971.png', '11973.png',
       '11989.png', '11990.png', '12005.png', '12006.png', '12020.png',
       '12030.png', '12059.png', '12152.png', '12157.png', '12166.png',
       '12169.png', '12171.png', '12185.png', '12187.png', '12193.png',
       '12196.png', '12211.png', '12214.png', '12253.png', '12254.png',
       '12276.png', '12277.png', '12278.png', '12281.png', '12370.png',
       '12401.png', '12404.png', '12444.png', '12519.png', '12553.png',
       '12577.png', '12584.png', '12646.png', '12655.png', '12656.png',
       '12671.png', '12676.png', '12706.png', '12757.png', '12758.png',
       '12769.png', '12786.png', '12787.png', '12817.png', '12902.png',
       '12910.png', '12940.png', '12962.png', '12965.png', '12973.png',
       '12982.png', '12986.png', '12988.png', '13032.png', '13059.png',
       '13063.png', '13086.png', '13100.png', '13108.png', '13112.png',
       '13113.png', '13126.png', '13152.png', '13241.png', '13268.png',
       '13271.png', '13279.png', '13286.png', '13309.png', '13334.png',
       '13424.png', '13436.png', '13456.png', '13458.png', '13462.png',
       '13466.png', '13476.png', '13506.png', '13509.png', '13528.png',
       '13529.png', '13531.png', '13538.png', '13541.png', '13561.png',
       '13581.png', '13588.png', '13679.png', '13696.png', '13698.png',
       '13714.png', '13716.png', '13758.png', '13763.png', '13781.png',
       '13786.png', '13794.png', '13834.png', '13872.png', '13874.png',
       '13893.png', '13969.png', '13976.png', '13981.png', '14002.png',
       '14031.png', '14042.png', '14089.png', '14100.png', '14139.png',
       '14158.png', '14174.png', '14179.png', '14200.png', '14236.png',
       '14271.png'], dtype=object)

In [9]:
# cable의 file name list화
cable = df.loc[df['class'] == 'cable', ['file_name']]['file_name'].values
cable

array(['10008.png', '10014.png', '10032.png', '10038.png', '10039.png',
       '10096.png', '10101.png', '10147.png', '10158.png', '10162.png',
       '10163.png', '10171.png', '10180.png', '10205.png', '10208.png',
       '10232.png', '10234.png', '10239.png', '10249.png', '10278.png',
       '10280.png', '10281.png', '10284.png', '10297.png', '10300.png',
       '10328.png', '10335.png', '10378.png', '10409.png', '10421.png',
       '10424.png', '10438.png', '10442.png', '10472.png', '10491.png',
       '10522.png', '10535.png', '10536.png', '10550.png', '10606.png',
       '10610.png', '10633.png', '10634.png', '10636.png', '10644.png',
       '10646.png', '10652.png', '10661.png', '10665.png', '10725.png',
       '10734.png', '10761.png', '10777.png', '10791.png', '10817.png',
       '10833.png', '10836.png', '10860.png', '10862.png', '10873.png',
       '10891.png', '10911.png', '10932.png', '10963.png', '10969.png',
       '10977.png', '11000.png', '11008.png', '11016.png', '11028.png',
       '11068.png', '11072.png', '11081.png', '11086.png', '11087.png',
       '11092.png', '11115.png', '11141.png', '11154.png', '11167.png',
       '11168.png', '11215.png', '11226.png', '11228.png', '11239.png',
       '11250.png', '11262.png', '11284.png', '11286.png', '11344.png',
       '11360.png', '11366.png', '11404.png', '11429.png', '11432.png',
       '11438.png', '11448.png', '11465.png', '11493.png', '11512.png',
       '11513.png', '11552.png', '11566.png', '11599.png', '11621.png',
       '11632.png', '11637.png', '11653.png', '11686.png', '11688.png',
       '11717.png', '11732.png', '11751.png', '11760.png', '11794.png',
       '11809.png', '11863.png', '11872.png', '11877.png', '11927.png',
       '11952.png', '11993.png', '12001.png', '12070.png', '12072.png',
       '12080.png', '12086.png', '12141.png', '12175.png', '12202.png',
       '12220.png', '12225.png', '12234.png', '12259.png', '12263.png',
       '12266.png', '12271.png', '12293.png', '12297.png', '12306.png',
       '12315.png', '12333.png', '12371.png', '12372.png', '12385.png',
       '12390.png', '12392.png', '12435.png', '12437.png', '12477.png',
       '12505.png', '12536.png', '12542.png', '12544.png', '12597.png',
       '12598.png', '12609.png', '12627.png', '12643.png', '12678.png',
       '12692.png', '12703.png', '12711.png', '12717.png', '12731.png',
       '12735.png', '12743.png', '12751.png', '12765.png', '12783.png',
       '12793.png', '12815.png', '12830.png', '12853.png', '12872.png',
       '12881.png', '12890.png', '12933.png', '12939.png', '12942.png',
       '12992.png', '13010.png', '13013.png', '13016.png', '13036.png',
       '13040.png', '13069.png', '13079.png', '13158.png', '13167.png',
       '13195.png', '13204.png', '13208.png', '13211.png', '13215.png',
       '13225.png', '13257.png', '13260.png', '13276.png', '13285.png',
       '13305.png', '13320.png', '13344.png', '13346.png', '13360.png',
       '13397.png', '13415.png', '13418.png', '13465.png', '13487.png',
       '13492.png', '13493.png', '13516.png', '13525.png', '13530.png',
       '13539.png', '13540.png', '13568.png', '13572.png', '13582.png',
       '13596.png', '13601.png', '13608.png', '13610.png', '13617.png',
       '13621.png', '13644.png', '13646.png', '13681.png', '13682.png',
       '13702.png', '13708.png', '13719.png', '13761.png', '13765.png',
       '13791.png', '13795.png', '13805.png', '13808.png', '13816.png',
       '13818.png', '13821.png', '13822.png', '13828.png', '13832.png',
       '13845.png', '13856.png', '13921.png', '13935.png', '13964.png',
       '13967.png', '13968.png', '14032.png', '14040.png', '14044.png',
       '14063.png', '14094.png', '14104.png', '14118.png', '14153.png',
       '14164.png', '14167.png', '14172.png', '14185.png', '14192.png',
       '14201.png', '14207.png', '14212.png', '14238.png', '14241.png',
       '14251.png'], dtype=object)

In [10]:
# capsule의 file name list화
capsule = df.loc[df['class'] == 'capsule', ['file_name']]['file_name'].values
capsule

array(['10001.png', '10006.png', '10022.png', '10024.png', '10080.png',
       '10100.png', '10110.png', '10111.png', '10113.png', '10118.png',
       '10156.png', '10181.png', '10189.png', '10255.png', '10263.png',
       '10286.png', '10298.png', '10317.png', '10330.png', '10343.png',
       '10347.png', '10436.png', '10444.png', '10473.png', '10497.png',
       '10510.png', '10521.png', '10546.png', '10603.png', '10604.png',
       '10617.png', '10625.png', '10651.png', '10676.png', '10695.png',
       '10720.png', '10731.png', '10778.png', '10785.png', '10796.png',
       '10807.png', '10815.png', '10847.png', '10876.png', '10896.png',
       '10903.png', '10920.png', '10947.png', '10960.png', '10962.png',
       '10979.png', '10999.png', '11002.png', '11012.png', '11020.png',
       '11043.png', '11061.png', '11069.png', '11112.png', '11117.png',
       '11124.png', '11135.png', '11162.png', '11175.png', '11211.png',
       '11223.png', '11230.png', '11232.png', '11244.png', '11266.png',
       '11271.png', '11285.png', '11299.png', '11309.png', '11319.png',
       '11336.png', '11355.png', '11356.png', '11372.png', '11375.png',
       '11376.png', '11415.png', '11440.png', '11491.png', '11558.png',
       '11568.png', '11572.png', '11577.png', '11592.png', '11595.png',
       '11597.png', '11613.png', '11636.png', '11648.png', '11656.png',
       '11663.png', '11669.png', '11672.png', '11697.png', '11699.png',
       '11703.png', '11720.png', '11722.png', '11747.png', '11766.png',
       '11779.png', '11785.png', '11786.png', '11787.png', '11801.png',
       '11811.png', '11812.png', '11826.png', '11843.png', '11865.png',
       '11869.png', '11902.png', '11903.png', '11904.png', '11908.png',
       '11914.png', '11938.png', '11944.png', '11946.png', '11953.png',
       '11984.png', '11999.png', '12024.png', '12067.png', '12077.png',
       '12093.png', '12094.png', '12111.png', '12121.png', '12129.png',
       '12135.png', '12204.png', '12205.png', '12212.png', '12222.png',
       '12236.png', '12244.png', '12270.png', '12283.png', '12289.png',
       '12311.png', '12331.png', '12357.png', '12358.png', '12361.png',
       '12375.png', '12378.png', '12424.png', '12438.png', '12443.png',
       '12470.png', '12483.png', '12484.png', '12503.png', '12509.png',
       '12521.png', '12548.png', '12552.png', '12567.png', '12579.png',
       '12592.png', '12611.png', '12632.png', '12681.png', '12687.png',
       '12698.png', '12715.png', '12719.png', '12720.png', '12723.png',
       '12734.png', '12739.png', '12746.png', '12755.png', '12767.png',
       '12774.png', '12781.png', '12813.png', '12816.png', '12842.png',
       '12848.png', '12850.png', '12852.png', '12855.png', '12893.png',
       '12903.png', '12922.png', '12946.png', '12948.png', '12966.png',
       '12984.png', '13009.png', '13014.png', '13018.png', '13039.png',
       '13046.png', '13061.png', '13064.png', '13075.png', '13076.png',
       '13093.png', '13135.png', '13136.png', '13147.png', '13153.png',
       '13154.png', '13185.png', '13188.png', '13218.png', '13221.png',
       '13251.png', '13269.png', '13282.png', '13293.png', '13303.png',
       '13338.png', '13352.png', '13402.png', '13411.png', '13414.png',
       '13423.png', '13440.png', '13442.png', '13455.png', '13473.png',
       '13474.png', '13480.png', '13495.png', '13524.png', '13592.png',
       '13629.png', '13684.png', '13686.png', '13690.png', '13729.png',
       '13732.png', '13819.png', '13835.png', '13838.png', '13843.png',
       '13849.png', '13850.png', '13869.png', '13907.png', '13913.png',
       '13951.png', '13960.png', '13975.png', '13998.png', '14003.png',
       '14004.png', '14006.png', '14019.png', '14035.png', '14041.png',
       '14043.png', '14048.png', '14050.png', '14060.png', '14073.png',
       '14105.png', '14134.png', '14138.png', '14180.png', '14189.png',
       '14194.png', '14198.png', '14217.png', '14218.png', '14269.png'],
      dtype=object)

In [11]:
# carpet의 file name list화
carpet = df.loc[df['class'] == 'carpet', ['file_name']]['file_name'].values
carpet

array(['10010.png', '10041.png', '10050.png', '10051.png', '10057.png',
       '10070.png', '10079.png', '10083.png', '10105.png', '10117.png',
       '10127.png', '10133.png', '10164.png', '10168.png', '10186.png',
       '10210.png', '10213.png', '10219.png', '10223.png', '10246.png',
       '10267.png', '10282.png', '10291.png', '10303.png', '10307.png',
       '10311.png', '10332.png', '10348.png', '10350.png', '10354.png',
       '10381.png', '10406.png', '10411.png', '10417.png', '10420.png',
       '10432.png', '10467.png', '10468.png', '10469.png', '10470.png',
       '10485.png', '10489.png', '10494.png', '10495.png', '10517.png',
       '10518.png', '10555.png', '10611.png', '10621.png', '10624.png',
       '10626.png', '10641.png', '10643.png', '10670.png', '10687.png',
       '10711.png', '10721.png', '10755.png', '10758.png', '10782.png',
       '10788.png', '10795.png', '10810.png', '10812.png', '10816.png',
       '10851.png', '10864.png', '10866.png', '10868.png', '10886.png',
       '10892.png', '10907.png', '10918.png', '10924.png', '10931.png',
       '10944.png', '10948.png', '10956.png', '10982.png', '10984.png',
       '10988.png', '10994.png', '10996.png', '10998.png', '11005.png',
       '11029.png', '11033.png', '11034.png', '11049.png', '11058.png',
       '11065.png', '11099.png', '11106.png', '11109.png', '11123.png',
       '11131.png', '11132.png', '11139.png', '11142.png', '11145.png',
       '11158.png', '11159.png', '11164.png', '11180.png', '11192.png',
       '11196.png', '11205.png', '11213.png', '11217.png', '11235.png',
       '11238.png', '11254.png', '11255.png', '11274.png', '11277.png',
       '11292.png', '11320.png', '11331.png', '11340.png', '11354.png',
       '11377.png', '11382.png', '11394.png', '11395.png', '11397.png',
       '11408.png', '11422.png', '11433.png', '11441.png', '11453.png',
       '11478.png', '11483.png', '11510.png', '11511.png', '11517.png',
       '11537.png', '11624.png', '11641.png', '11673.png', '11704.png',
       '11726.png', '11742.png', '11754.png', '11756.png', '11775.png',
       '11783.png', '11784.png', '11813.png', '11835.png', '11845.png',
       '11846.png', '11858.png', '11859.png', '11862.png', '11883.png',
       '11891.png', '11922.png', '11924.png', '11926.png', '11939.png',
       '11950.png', '11956.png', '11960.png', '11980.png', '11983.png',
       '11997.png', '12007.png', '12010.png', '12014.png', '12116.png',
       '12137.png', '12140.png', '12148.png', '12174.png', '12182.png',
       '12194.png', '12209.png', '12260.png', '12267.png', '12274.png',
       '12285.png', '12305.png', '12310.png', '12318.png', '12329.png',
       '12334.png', '12351.png', '12363.png', '12382.png', '12410.png',
       '12414.png', '12415.png', '12425.png', '12426.png', '12432.png',
       '12441.png', '12459.png', '12481.png', '12487.png', '12497.png',
       '12499.png', '12522.png', '12533.png', '12543.png', '12560.png',
       '12562.png', '12569.png', '12578.png', '12603.png', '12612.png',
       '12645.png', '12652.png', '12662.png', '12664.png', '12669.png',
       '12705.png', '12708.png', '12709.png', '12736.png', '12742.png',
       '12802.png', '12811.png', '12823.png', '12826.png', '12828.png',
       '12833.png', '12856.png', '12865.png', '12878.png', '12879.png',
       '12895.png', '12897.png', '12900.png', '12915.png', '12928.png',
       '12949.png', '12954.png', '12967.png', '12994.png', '13005.png',
       '13025.png', '13031.png', '13042.png', '13055.png', '13068.png',
       '13073.png', '13080.png', '13083.png', '13089.png', '13105.png',
       '13117.png', '13121.png', '13124.png', '13131.png', '13141.png',
       '13164.png', '13172.png', '13177.png', '13199.png', '13205.png',
       '13247.png', '13261.png', '13267.png', '13299.png', '13310.png',
       '13339.png', '13355.png', '13368.png', '13407.png', '13419.png',
       '13437.png', '13448.png', '13477.png', '13484.png', '13499.png',
       '13503.png', '13534.png', '13535.png', '13543.png', '13577.png',
       '13605.png', '13613.png', '13620.png', '13624.png', '13632.png',
       '13635.png', '13663.png', '13672.png', '13678.png', '13687.png',
       '13697.png', '13705.png', '13745.png', '13759.png', '13785.png',
       '13797.png', '13798.png', '13802.png', '13803.png', '13813.png',
       '13829.png', '13889.png', '13894.png', '13903.png', '13908.png',
       '13927.png', '13934.png', '13940.png', '13946.png', '13950.png',
       '13961.png', '13974.png', '13992.png', '14007.png', '14013.png',
       '14021.png', '14030.png', '14058.png', '14059.png', '14075.png',
       '14117.png', '14125.png', '14156.png', '14182.png', '14213.png',
       '14225.png', '14229.png'], dtype=object)

In [12]:
# grid의 file name list화
grid = df.loc[df['class'] == 'grid', ['file_name']]['file_name'].values
grid

array(['10056.png', '10062.png', '10084.png', '10150.png', '10151.png',
       '10178.png', '10188.png', '10211.png', '10222.png', '10229.png',
       '10285.png', '10292.png', '10302.png', '10306.png', '10323.png',
       '10329.png', '10360.png', '10370.png', '10373.png', '10374.png',
       '10408.png', '10428.png', '10464.png', '10481.png', '10509.png',
       '10559.png', '10582.png', '10586.png', '10590.png', '10592.png',
       '10596.png', '10608.png', '10623.png', '10630.png', '10632.png',
       '10647.png', '10648.png', '10658.png', '10679.png', '10696.png',
       '10717.png', '10737.png', '10743.png', '10768.png', '10780.png',
       '10937.png', '10951.png', '10961.png', '10971.png', '10978.png',
       '10980.png', '10986.png', '11024.png', '11025.png', '11040.png',
       '11045.png', '11085.png', '11088.png', '11093.png', '11094.png',
       '11103.png', '11119.png', '11177.png', '11178.png', '11179.png',
       '11182.png', '11195.png', '11201.png', '11222.png', '11225.png',
       '11237.png', '11245.png', '11259.png', '11272.png', '11288.png',
       '11297.png', '11303.png', '11315.png', '11318.png', '11324.png',
       '11328.png', '11345.png', '11350.png', '11359.png', '11361.png',
       '11365.png', '11386.png', '11392.png', '11413.png', '11425.png',
       '11468.png', '11470.png', '11481.png', '11535.png', '11545.png',
       '11556.png', '11561.png', '11562.png', '11571.png', '11581.png',
       '11640.png', '11655.png', '11671.png', '11679.png', '11682.png',
       '11687.png', '11692.png', '11701.png', '11737.png', '11764.png',
       '11769.png', '11777.png', '11793.png', '11798.png', '11803.png',
       '11810.png', '11817.png', '11829.png', '11870.png', '11871.png',
       '11882.png', '11888.png', '11890.png', '11892.png', '11919.png',
       '11923.png', '11925.png', '11934.png', '11937.png', '11976.png',
       '11979.png', '11985.png', '11998.png', '12022.png', '12028.png',
       '12029.png', '12038.png', '12041.png', '12049.png', '12057.png',
       '12079.png', '12081.png', '12084.png', '12107.png', '12123.png',
       '12125.png', '12154.png', '12206.png', '12216.png', '12230.png',
       '12238.png', '12249.png', '12256.png', '12257.png', '12262.png',
       '12342.png', '12356.png', '12360.png', '12388.png', '12397.png',
       '12406.png', '12417.png', '12449.png', '12455.png', '12472.png',
       '12493.png', '12496.png', '12529.png', '12538.png', '12550.png',
       '12561.png', '12580.png', '12585.png', '12595.png', '12600.png',
       '12617.png', '12653.png', '12661.png', '12668.png', '12670.png',
       '12693.png', '12713.png', '12718.png', '12744.png', '12753.png',
       '12761.png', '12762.png', '12775.png', '12792.png', '12798.png',
       '12803.png', '12820.png', '12827.png', '12837.png', '12841.png',
       '12860.png', '12866.png', '12883.png', '12888.png', '12889.png',
       '12907.png', '12935.png', '12943.png', '12959.png', '12969.png',
       '13008.png', '13012.png', '13056.png', '13067.png', '13097.png',
       '13116.png', '13123.png', '13161.png', '13170.png', '13175.png',
       '13186.png', '13189.png', '13214.png', '13234.png', '13252.png',
       '13253.png', '13254.png', '13270.png', '13278.png', '13316.png',
       '13337.png', '13343.png', '13358.png', '13363.png', '13392.png',
       '13425.png', '13472.png', '13481.png', '13512.png', '13514.png',
       '13549.png', '13552.png', '13557.png', '13558.png', '13574.png',
       '13603.png', '13609.png', '13622.png', '13641.png', '13651.png',
       '13653.png', '13676.png', '13677.png', '13680.png', '13689.png',
       '13693.png', '13706.png', '13709.png', '13750.png', '13778.png',
       '13792.png', '13796.png', '13823.png', '13826.png', '13841.png',
       '13858.png', '13886.png', '13887.png', '13895.png', '13901.png',
       '13911.png', '13915.png', '13926.png', '13928.png', '13932.png',
       '13948.png', '13958.png', '13982.png', '13989.png', '13990.png',
       '13993.png', '14023.png', '14045.png', '14047.png', '14084.png',
       '14098.png', '14143.png', '14146.png', '14151.png', '14166.png',
       '14169.png', '14177.png', '14210.png', '14214.png', '14233.png',
       '14260.png', '14263.png', '14266.png', '14274.png'], dtype=object)

In [13]:
# hazelnut의 file name list화
hazelnut = df.loc[df['class'] == 'hazelnut', ['file_name']]['file_name'].values
hazelnut

array(['10011.png', '10025.png', '10031.png', '10033.png', '10064.png',
       '10076.png', '10085.png', '10087.png', '10089.png', '10102.png',
       '10107.png', '10125.png', '10134.png', '10136.png', '10152.png',
       '10161.png', '10173.png', '10177.png', '10185.png', '10200.png',
       '10203.png', '10214.png', '10215.png', '10224.png', '10245.png',
       '10258.png', '10269.png', '10274.png', '10295.png', '10301.png',
       '10312.png', '10318.png', '10322.png', '10334.png', '10349.png',
       '10369.png', '10389.png', '10395.png', '10397.png', '10398.png',
       '10405.png', '10433.png', '10443.png', '10446.png', '10450.png',
       '10454.png', '10465.png', '10466.png', '10471.png', '10475.png',
       '10477.png', '10500.png', '10506.png', '10515.png', '10516.png',
       '10519.png', '10529.png', '10532.png', '10538.png', '10539.png',
       '10541.png', '10560.png', '10562.png', '10572.png', '10576.png',
       '10599.png', '10607.png', '10637.png', '10673.png', '10688.png',
       '10703.png', '10710.png', '10713.png', '10714.png', '10719.png',
       '10738.png', '10808.png', '10822.png', '10840.png', '10848.png',
       '10865.png', '10880.png', '10881.png', '10882.png', '10884.png',
       '10889.png', '10897.png', '10906.png', '10926.png', '10935.png',
       '10942.png', '10954.png', '10957.png', '10967.png', '10974.png',
       '10997.png', '11026.png', '11044.png', '11046.png', '11048.png',
       '11052.png', '11073.png', '11095.png', '11114.png', '11116.png',
       '11118.png', '11126.png', '11130.png', '11160.png', '11172.png',
       '11185.png', '11207.png', '11208.png', '11209.png', '11234.png',
       '11246.png', '11263.png', '11265.png', '11270.png', '11276.png',
       '11279.png', '11280.png', '11282.png', '11326.png', '11330.png',
       '11343.png', '11364.png', '11387.png', '11388.png', '11390.png',
       '11391.png', '11396.png', '11431.png', '11434.png', '11437.png',
       '11443.png', '11450.png', '11467.png', '11469.png', '11482.png',
       '11485.png', '11494.png', '11498.png', '11504.png', '11505.png',
       '11509.png', '11515.png', '11519.png', '11521.png', '11526.png',
       '11533.png', '11540.png', '11557.png', '11560.png', '11591.png',
       '11616.png', '11618.png', '11626.png', '11627.png', '11630.png',
       '11633.png', '11645.png', '11659.png', '11694.png', '11696.png',
       '11710.png', '11719.png', '11724.png', '11736.png', '11746.png',
       '11748.png', '11757.png', '11758.png', '11761.png', '11762.png',
       '11768.png', '11788.png', '11814.png', '11816.png', '11821.png',
       '11836.png', '11849.png', '11851.png', '11857.png', '11884.png',
       '11901.png', '11918.png', '11931.png', '11942.png', '11975.png',
       '12004.png', '12008.png', '12017.png', '12034.png', '12037.png',
       '12055.png', '12063.png', '12078.png', '12088.png', '12090.png',
       '12098.png', '12102.png', '12146.png', '12158.png', '12172.png',
       '12173.png', '12181.png', '12197.png', '12201.png', '12246.png',
       '12258.png', '12280.png', '12282.png', '12288.png', '12299.png',
       '12300.png', '12312.png', '12319.png', '12324.png', '12348.png',
       '12354.png', '12367.png', '12373.png', '12394.png', '12402.png',
       '12405.png', '12411.png', '12412.png', '12429.png', '12431.png',
       '12442.png', '12445.png', '12446.png', '12454.png', '12479.png',
       '12486.png', '12491.png', '12494.png', '12498.png', '12507.png',
       '12513.png', '12530.png', '12537.png', '12546.png', '12557.png',
       '12570.png', '12573.png', '12576.png', '12593.png', '12602.png',
       '12606.png', '12607.png', '12615.png', '12619.png', '12624.png',
       '12628.png', '12635.png', '12641.png', '12647.png', '12659.png',
       '12673.png', '12679.png', '12682.png', '12696.png', '12700.png',
       '12702.png', '12707.png', '12714.png', '12727.png', '12729.png',
       '12738.png', '12740.png', '12756.png', '12759.png', '12764.png',
       '12770.png', '12776.png', '12788.png', '12791.png', '12797.png',
       '12809.png', '12822.png', '12829.png', '12836.png', '12843.png',
       '12846.png', '12862.png', '12864.png', '12877.png', '12891.png',
       '12901.png', '12914.png', '12924.png', '12926.png', '12941.png',
       '12952.png', '12953.png', '12963.png', '12970.png', '12989.png',
       '13002.png', '13020.png', '13026.png', '13033.png', '13045.png',
       '13070.png', '13087.png', '13090.png', '13096.png', '13102.png',
       '13109.png', '13110.png', '13128.png', '13140.png', '13151.png',
       '13160.png', '13162.png', '13163.png', '13169.png', '13200.png',
       '13217.png', '13235.png', '13237.png', '13240.png', '13258.png',
       '13263.png', '13283.png', '13284.png', '13296.png', '13304.png',
       '13311.png', '13313.png', '13314.png', '13318.png', '13323.png',
       '13326.png', '13340.png', '13345.png', '13348.png', '13367.png',
       '13380.png', '13382.png', '13395.png', '13406.png', '13408.png',
       '13427.png', '13445.png', '13446.png', '13461.png', '13463.png',
       '13489.png', '13508.png', '13513.png', '13518.png', '13526.png',
       '13547.png', '13556.png', '13562.png', '13563.png', '13576.png',
       '13579.png', '13634.png', '13639.png', '13655.png', '13666.png',
       '13683.png', '13694.png', '13703.png', '13704.png', '13726.png',
       '13727.png', '13730.png', '13735.png', '13739.png', '13741.png',
       '13769.png', '13774.png', '13809.png', '13825.png', '13833.png',
       '13842.png', '13860.png', '13862.png', '13865.png', '13873.png',
       '13876.png', '13890.png', '13906.png', '13912.png', '13918.png',
       '13939.png', '13956.png', '13959.png', '13983.png', '13997.png',
       '14008.png', '14016.png', '14018.png', '14025.png', '14026.png',
       '14029.png', '14052.png', '14056.png', '14078.png', '14083.png',
       '14086.png', '14096.png', '14097.png', '14115.png', '14126.png',
       '14132.png', '14142.png', '14144.png', '14145.png', '14157.png',
       '14173.png', '14206.png', '14220.png', '14231.png', '14235.png',
       '14247.png', '14249.png', '14256.png', '14257.png', '14258.png',
       '14267.png', '14268.png'], dtype=object)

In [14]:
# leather의 file name list화
leather = df.loc[df['class'] == 'leather', ['file_name']]['file_name'].values
leather

array(['10021.png', '10066.png', '10067.png', '10074.png', '10077.png',
       '10109.png', '10115.png', '10149.png', '10154.png', '10160.png',
       '10179.png', '10195.png', '10218.png', '10230.png', '10233.png',
       '10253.png', '10276.png', '10277.png', '10279.png', '10314.png',
       '10316.png', '10324.png', '10327.png', '10333.png', '10338.png',
       '10345.png', '10387.png', '10414.png', '10423.png', '10455.png',
       '10499.png', '10523.png', '10528.png', '10563.png', '10568.png',
       '10579.png', '10588.png', '10598.png', '10612.png', '10615.png',
       '10618.png', '10631.png', '10650.png', '10656.png', '10663.png',
       '10664.png', '10678.png', '10706.png', '10739.png', '10740.png',
       '10746.png', '10765.png', '10771.png', '10786.png', '10825.png',
       '10877.png', '10883.png', '10909.png', '10919.png', '10927.png',
       '10958.png', '10965.png', '10972.png', '10973.png', '10976.png',
       '10985.png', '10987.png', '10990.png', '11014.png', '11032.png',
       '11037.png', '11038.png', '11125.png', '11163.png', '11171.png',
       '11193.png', '11203.png', '11210.png', '11233.png', '11240.png',
       '11267.png', '11268.png', '11294.png', '11305.png', '11316.png',
       '11370.png', '11373.png', '11379.png', '11385.png', '11399.png',
       '11406.png', '11412.png', '11445.png', '11462.png', '11477.png',
       '11490.png', '11492.png', '11506.png', '11507.png', '11520.png',
       '11527.png', '11529.png', '11531.png', '11542.png', '11543.png',
       '11564.png', '11574.png', '11583.png', '11584.png', '11586.png',
       '11605.png', '11623.png', '11631.png', '11638.png', '11674.png',
       '11706.png', '11714.png', '11733.png', '11738.png', '11789.png',
       '11792.png', '11819.png', '11838.png', '11842.png', '11847.png',
       '11874.png', '11895.png', '11900.png', '11920.png', '11921.png',
       '11935.png', '11948.png', '11968.png', '11991.png', '12023.png',
       '12032.png', '12047.png', '12053.png', '12056.png', '12066.png',
       '12076.png', '12082.png', '12110.png', '12113.png', '12126.png',
       '12144.png', '12156.png', '12160.png', '12161.png', '12195.png',
       '12208.png', '12210.png', '12242.png', '12247.png', '12294.png',
       '12301.png', '12309.png', '12323.png', '12335.png', '12340.png',
       '12341.png', '12377.png', '12413.png', '12416.png', '12418.png',
       '12421.png', '12422.png', '12430.png', '12434.png', '12451.png',
       '12452.png', '12462.png', '12465.png', '12473.png', '12502.png',
       '12506.png', '12524.png', '12568.png', '12594.png', '12604.png',
       '12629.png', '12650.png', '12675.png', '12684.png', '12716.png',
       '12722.png', '12737.png', '12750.png', '12752.png', '12777.png',
       '12839.png', '12845.png', '12851.png', '12859.png', '12867.png',
       '12868.png', '12906.png', '12909.png', '12920.png', '12974.png',
       '12978.png', '12983.png', '13001.png', '13062.png', '13091.png',
       '13092.png', '13101.png', '13104.png', '13137.png', '13166.png',
       '13174.png', '13184.png', '13230.png', '13232.png', '13233.png',
       '13243.png', '13244.png', '13249.png', '13288.png', '13298.png',
       '13312.png', '13332.png', '13333.png', '13356.png', '13400.png',
       '13403.png', '13413.png', '13438.png', '13447.png', '13451.png',
       '13452.png', '13488.png', '13515.png', '13520.png', '13537.png',
       '13560.png', '13569.png', '13571.png', '13573.png', '13602.png',
       '13607.png', '13628.png', '13643.png', '13645.png', '13650.png',
       '13654.png', '13659.png', '13662.png', '13664.png', '13713.png',
       '13715.png', '13734.png', '13737.png', '13748.png', '13754.png',
       '13790.png', '13801.png', '13811.png', '13812.png', '13817.png',
       '13840.png', '13848.png', '13881.png', '13885.png', '13897.png',
       '13900.png', '13904.png', '13916.png', '13930.png', '13954.png',
       '13977.png', '13978.png', '13999.png', '14001.png', '14010.png',
       '14017.png', '14024.png', '14033.png', '14051.png', '14072.png',
       '14111.png', '14112.png', '14122.png', '14129.png', '14152.png',
       '14165.png', '14209.png', '14219.png', '14222.png', '14237.png',
       '14245.png', '14264.png', '14265.png'], dtype=object)

In [15]:
# metal_nut의 file name list화
metal_nut = df.loc[df['class']=='metal_nut', ['file_name']]['file_name'].values
metal_nut

array(['10016.png', '10047.png', '10093.png', '10099.png', '10103.png',
       '10106.png', '10122.png', '10132.png', '10142.png', '10166.png',
       '10184.png', '10191.png', '10198.png', '10220.png', '10226.png',
       '10250.png', '10256.png', '10265.png', '10275.png', '10288.png',
       '10294.png', '10315.png', '10326.png', '10331.png', '10353.png',
       '10359.png', '10388.png', '10402.png', '10431.png', '10440.png',
       '10461.png', '10493.png', '10501.png', '10502.png', '10507.png',
       '10508.png', '10513.png', '10525.png', '10531.png', '10547.png',
       '10585.png', '10593.png', '10594.png', '10609.png', '10620.png',
       '10628.png', '10640.png', '10655.png', '10660.png', '10682.png',
       '10691.png', '10707.png', '10708.png', '10722.png', '10745.png',
       '10762.png', '10805.png', '10819.png', '10823.png', '10831.png',
       '10853.png', '10856.png', '10878.png', '10900.png', '10928.png',
       '10936.png', '10955.png', '10966.png', '10989.png', '11013.png',
       '11019.png', '11021.png', '11035.png', '11054.png', '11062.png',
       '11066.png', '11128.png', '11150.png', '11169.png', '11181.png',
       '11183.png', '11189.png', '11194.png', '11212.png', '11242.png',
       '11258.png', '11260.png', '11278.png', '11287.png', '11298.png',
       '11300.png', '11308.png', '11312.png', '11313.png', '11314.png',
       '11333.png', '11339.png', '11349.png', '11402.png', '11410.png',
       '11411.png', '11423.png', '11439.png', '11444.png', '11452.png',
       '11471.png', '11475.png', '11476.png', '11480.png', '11488.png',
       '11500.png', '11503.png', '11523.png', '11570.png', '11579.png',
       '11585.png', '11666.png', '11677.png', '11690.png', '11725.png',
       '11745.png', '11772.png', '11781.png', '11800.png', '11807.png',
       '11818.png', '11820.png', '11823.png', '11827.png', '11831.png',
       '11832.png', '11928.png', '11940.png', '11954.png', '11957.png',
       '11958.png', '11959.png', '12002.png', '12011.png', '12044.png',
       '12050.png', '12052.png', '12061.png', '12071.png', '12085.png',
       '12091.png', '12101.png', '12112.png', '12151.png', '12177.png',
       '12179.png', '12223.png', '12304.png', '12307.png', '12322.png',
       '12328.png', '12347.png', '12393.png', '12420.png', '12439.png',
       '12467.png', '12495.png', '12545.png', '12559.png', '12574.png',
       '12582.png', '12588.png', '12618.png', '12622.png', '12638.png',
       '12666.png', '12677.png', '12689.png', '12732.png', '12810.png',
       '12824.png', '12861.png', '12870.png', '12871.png', '12882.png',
       '12887.png', '12911.png', '12919.png', '12947.png', '12957.png',
       '12968.png', '12975.png', '12977.png', '12990.png', '12991.png',
       '13030.png', '13043.png', '13044.png', '13057.png', '13060.png',
       '13077.png', '13107.png', '13122.png', '13125.png', '13133.png',
       '13142.png', '13144.png', '13198.png', '13236.png', '13250.png',
       '13262.png', '13266.png', '13294.png', '13307.png', '13351.png',
       '13354.png', '13364.png', '13384.png', '13404.png', '13429.png',
       '13454.png', '13469.png', '13502.png', '13522.png', '13544.png',
       '13548.png', '13564.png', '13585.png', '13590.png', '13597.png',
       '13606.png', '13611.png', '13657.png', '13673.png', '13691.png',
       '13710.png', '13740.png', '13747.png', '13804.png', '13830.png',
       '13831.png', '13836.png', '13852.png', '13861.png', '13868.png',
       '13924.png', '13937.png', '13938.png', '13955.png', '13984.png',
       '13985.png', '13986.png', '14005.png', '14036.png', '14067.png',
       '14076.png', '14088.png', '14092.png', '14103.png', '14107.png',
       '14114.png', '14116.png', '14124.png', '14131.png', '14141.png',
       '14150.png', '14161.png', '14163.png', '14216.png', '14228.png',
       '14239.png', '14261.png', '14262.png'], dtype=object)

In [16]:
# pill의 file name list화
pill = df.loc[df['class']=='pill', ['file_name']]['file_name'].values
pill

array(['10013.png', '10018.png', '10023.png', '10028.png', '10034.png',
       '10054.png', '10082.png', '10086.png', '10092.png', '10104.png',
       '10121.png', '10183.png', '10225.png', '10243.png', '10287.png',
       '10299.png', '10305.png', '10310.png', '10358.png', '10390.png',
       '10393.png', '10394.png', '10407.png', '10413.png', '10460.png',
       '10462.png', '10476.png', '10490.png', '10496.png', '10504.png',
       '10526.png', '10534.png', '10543.png', '10556.png', '10558.png',
       '10571.png', '10589.png', '10591.png', '10613.png', '10642.png',
       '10649.png', '10657.png', '10662.png', '10671.png', '10675.png',
       '10677.png', '10686.png', '10690.png', '10694.png', '10709.png',
       '10736.png', '10742.png', '10748.png', '10749.png', '10754.png',
       '10764.png', '10804.png', '10806.png', '10813.png', '10820.png',
       '10830.png', '10845.png', '10846.png', '10855.png', '10857.png',
       '10905.png', '10914.png', '10922.png', '10930.png', '10939.png',
       '10941.png', '10970.png', '10981.png', '10983.png', '11001.png',
       '11003.png', '11011.png', '11027.png', '11042.png', '11055.png',
       '11063.png', '11076.png', '11090.png', '11091.png', '11127.png',
       '11147.png', '11148.png', '11151.png', '11152.png', '11173.png',
       '11174.png', '11184.png', '11241.png', '11249.png', '11251.png',
       '11269.png', '11306.png', '11317.png', '11322.png', '11327.png',
       '11335.png', '11337.png', '11342.png', '11371.png', '11381.png',
       '11384.png', '11393.png', '11409.png', '11414.png', '11418.png',
       '11419.png', '11451.png', '11461.png', '11489.png', '11497.png',
       '11508.png', '11514.png', '11530.png', '11546.png', '11548.png',
       '11550.png', '11565.png', '11578.png', '11587.png', '11589.png',
       '11603.png', '11611.png', '11619.png', '11620.png', '11646.png',
       '11651.png', '11665.png', '11670.png', '11676.png', '11691.png',
       '11695.png', '11707.png', '11712.png', '11740.png', '11767.png',
       '11774.png', '11776.png', '11822.png', '11825.png', '11848.png',
       '11856.png', '11864.png', '11867.png', '11879.png', '11880.png',
       '11881.png', '11898.png', '11930.png', '11933.png', '11945.png',
       '11955.png', '11963.png', '11966.png', '11978.png', '11987.png',
       '11996.png', '12003.png', '12062.png', '12064.png', '12074.png',
       '12089.png', '12100.png', '12103.png', '12130.png', '12131.png',
       '12139.png', '12145.png', '12150.png', '12167.png', '12176.png',
       '12189.png', '12190.png', '12192.png', '12200.png', '12221.png',
       '12227.png', '12229.png', '12231.png', '12251.png', '12261.png',
       '12272.png', '12273.png', '12291.png', '12314.png', '12316.png',
       '12320.png', '12325.png', '12349.png', '12369.png', '12376.png',
       '12380.png', '12389.png', '12391.png', '12409.png', '12423.png',
       '12428.png', '12440.png', '12448.png', '12458.png', '12488.png',
       '12489.png', '12490.png', '12511.png', '12514.png', '12517.png',
       '12526.png', '12527.png', '12531.png', '12534.png', '12540.png',
       '12572.png', '12586.png', '12614.png', '12620.png', '12631.png',
       '12651.png', '12663.png', '12665.png', '12690.png', '12697.png',
       '12699.png', '12726.png', '12730.png', '12766.png', '12782.png',
       '12790.png', '12806.png', '12808.png', '12825.png', '12849.png',
       '12854.png', '12898.png', '12916.png', '12956.png', '12971.png',
       '13000.png', '13011.png', '13022.png', '13054.png', '13065.png',
       '13078.png', '13085.png', '13088.png', '13099.png', '13103.png',
       '13120.png', '13130.png', '13132.png', '13145.png', '13148.png',
       '13149.png', '13150.png', '13157.png', '13180.png', '13191.png',
       '13193.png', '13227.png', '13229.png', '13242.png', '13272.png',
       '13273.png', '13324.png', '13341.png', '13361.png', '13366.png',
       '13371.png', '13375.png', '13387.png', '13394.png', '13398.png',
       '13401.png', '13410.png', '13426.png', '13430.png', '13433.png',
       '13444.png', '13449.png', '13468.png', '13471.png', '13486.png',
       '13494.png', '13497.png', '13500.png', '13504.png', '13536.png',
       '13553.png', '13555.png', '13566.png', '13591.png', '13604.png',
       '13631.png', '13665.png', '13669.png', '13674.png', '13700.png',
       '13701.png', '13722.png', '13723.png', '13728.png', '13736.png',
       '13738.png', '13744.png', '13755.png', '13756.png', '13762.png',
       '13777.png', '13783.png', '13784.png', '13800.png', '13820.png',
       '13837.png', '13847.png', '13854.png', '13870.png', '13879.png',
       '13883.png', '13905.png', '13910.png', '13917.png', '13925.png',
       '13942.png', '13945.png', '13952.png', '13987.png', '14015.png',
       '14055.png', '14101.png', '14113.png', '14130.png', '14140.png',
       '14154.png', '14183.png', '14199.png', '14221.png', '14252.png'],
      dtype=object)

In [17]:
screw = df.loc[df['class']=='screw', ['file_name']]['file_name'].values
screw

array(['10007.png', '10019.png', '10035.png', '10044.png', '10046.png',
       '10065.png', '10068.png', '10069.png', '10090.png', '10095.png',
       '10114.png', '10120.png', '10123.png', '10124.png', '10126.png',
       '10130.png', '10137.png', '10139.png', '10141.png', '10165.png',
       '10167.png', '10169.png', '10197.png', '10201.png', '10206.png',
       '10231.png', '10238.png', '10242.png', '10270.png', '10272.png',
       '10273.png', '10293.png', '10304.png', '10309.png', '10313.png',
       '10336.png', '10344.png', '10346.png', '10365.png', '10367.png',
       '10368.png', '10376.png', '10386.png', '10416.png', '10418.png',
       '10422.png', '10427.png', '10448.png', '10452.png', '10453.png',
       '10456.png', '10479.png', '10483.png', '10492.png', '10498.png',
       '10503.png', '10527.png', '10549.png', '10564.png', '10587.png',
       '10614.png', '10705.png', '10735.png', '10752.png', '10766.png',
       '10769.png', '10770.png', '10773.png', '10776.png', '10783.png',
       '10842.png', '10844.png', '10850.png', '10852.png', '10858.png',
       '10867.png', '10874.png', '10888.png', '10904.png', '10921.png',
       '10933.png', '10940.png', '10943.png', '10946.png', '10953.png',
       '10964.png', '11004.png', '11015.png', '11031.png', '11050.png',
       '11067.png', '11074.png', '11078.png', '11084.png', '11089.png',
       '11096.png', '11097.png', '11100.png', '11101.png', '11104.png',
       '11105.png', '11108.png', '11110.png', '11121.png', '11129.png',
       '11138.png', '11144.png', '11155.png', '11157.png', '11166.png',
       '11186.png', '11216.png', '11220.png', '11224.png', '11236.png',
       '11321.png', '11325.png', '11367.png', '11380.png', '11398.png',
       '11405.png', '11417.png', '11442.png', '11446.png', '11447.png',
       '11454.png', '11457.png', '11464.png', '11501.png', '11502.png',
       '11522.png', '11525.png', '11528.png', '11544.png', '11549.png',
       '11553.png', '11563.png', '11567.png', '11580.png', '11604.png',
       '11606.png', '11607.png', '11609.png', '11610.png', '11617.png',
       '11643.png', '11644.png', '11650.png', '11660.png', '11668.png',
       '11705.png', '11727.png', '11744.png', '11765.png', '11771.png',
       '11780.png', '11802.png', '11808.png', '11830.png', '11868.png',
       '11886.png', '11893.png', '11899.png', '11909.png', '11910.png',
       '11943.png', '11964.png', '11969.png', '11970.png', '11972.png',
       '11977.png', '12021.png', '12025.png', '12042.png', '12075.png',
       '12092.png', '12109.png', '12114.png', '12120.png', '12132.png',
       '12138.png', '12147.png', '12153.png', '12165.png', '12168.png',
       '12215.png', '12217.png', '12218.png', '12219.png', '12228.png',
       '12233.png', '12245.png', '12265.png', '12268.png', '12275.png',
       '12308.png', '12317.png', '12326.png', '12336.png', '12337.png',
       '12343.png', '12344.png', '12365.png', '12368.png', '12381.png',
       '12387.png', '12396.png', '12400.png', '12433.png', '12456.png',
       '12457.png', '12468.png', '12478.png', '12485.png', '12504.png',
       '12512.png', '12515.png', '12516.png', '12518.png', '12523.png',
       '12535.png', '12555.png', '12566.png', '12571.png', '12583.png',
       '12625.png', '12626.png', '12633.png', '12639.png', '12660.png',
       '12694.png', '12721.png', '12724.png', '12725.png', '12741.png',
       '12763.png', '12768.png', '12778.png', '12780.png', '12795.png',
       '12799.png', '12800.png', '12875.png', '12892.png', '12894.png',
       '12899.png', '12905.png', '12917.png', '12921.png', '12923.png',
       '12929.png', '12937.png', '12950.png', '12960.png', '12979.png',
       '12995.png', '13004.png', '13007.png', '13019.png', '13024.png',
       '13038.png', '13053.png', '13071.png', '13081.png', '13094.png',
       '13106.png', '13114.png', '13118.png', '13138.png', '13146.png',
       '13165.png', '13173.png', '13176.png', '13178.png', '13182.png',
       '13201.png', '13206.png', '13216.png', '13222.png', '13238.png',
       '13255.png', '13264.png', '13275.png', '13308.png', '13349.png',
       '13365.png', '13369.png', '13377.png', '13378.png', '13379.png',
       '13385.png', '13386.png', '13396.png', '13421.png', '13422.png',
       '13431.png', '13439.png', '13460.png', '13467.png', '13478.png',
       '13479.png', '13483.png', '13485.png', '13490.png', '13496.png',
       '13501.png', '13507.png', '13510.png', '13517.png', '13519.png',
       '13523.png', '13532.png', '13542.png', '13545.png', '13550.png',
       '13551.png', '13570.png', '13587.png', '13627.png', '13630.png',
       '13637.png', '13642.png', '13648.png', '13658.png', '13685.png',
       '13695.png', '13720.png', '13733.png', '13743.png', '13753.png',
       '13766.png', '13779.png', '13788.png', '13793.png', '13810.png',
       '13815.png', '13844.png', '13846.png', '13855.png', '13859.png',
       '13867.png', '13888.png', '13891.png', '13902.png', '13919.png',
       '13957.png', '13963.png', '13965.png', '13980.png', '13994.png',
       '14009.png', '14022.png', '14037.png', '14054.png', '14057.png',
       '14066.png', '14068.png', '14071.png', '14074.png', '14077.png',
       '14079.png', '14080.png', '14082.png', '14087.png', '14091.png',
       '14095.png', '14127.png', '14133.png', '14135.png', '14136.png',
       '14148.png', '14155.png', '14175.png', '14181.png', '14187.png',
       '14190.png', '14223.png', '14234.png', '14246.png', '14253.png',
       '14276.png'], dtype=object)

In [18]:
# tile의 file name list화
tile = df.loc[df['class']=='tile', ['file_name']]['file_name'].values
tile

array(['10037.png', '10045.png', '10055.png', '10075.png', '10108.png',
       '10129.png', '10145.png', '10155.png', '10157.png', '10170.png',
       '10175.png', '10187.png', '10190.png', '10209.png', '10227.png',
       '10247.png', '10254.png', '10264.png', '10271.png', '10319.png',
       '10339.png', '10342.png', '10351.png', '10356.png', '10363.png',
       '10380.png', '10383.png', '10400.png', '10410.png', '10425.png',
       '10429.png', '10459.png', '10463.png', '10487.png', '10505.png',
       '10511.png', '10512.png', '10533.png', '10548.png', '10565.png',
       '10597.png', '10602.png', '10616.png', '10627.png', '10667.png',
       '10668.png', '10680.png', '10685.png', '10689.png', '10693.png',
       '10697.png', '10704.png', '10718.png', '10724.png', '10727.png',
       '10728.png', '10732.png', '10747.png', '10787.png', '10790.png',
       '10797.png', '10803.png', '10809.png', '10814.png', '10829.png',
       '10835.png', '10838.png', '10869.png', '10890.png', '10895.png',
       '10901.png', '10910.png', '10929.png', '10945.png', '11009.png',
       '11036.png', '11039.png', '11071.png', '11079.png', '11098.png',
       '11107.png', '11113.png', '11149.png', '11165.png', '11206.png',
       '11219.png', '11289.png', '11293.png', '11301.png', '11334.png',
       '11421.png', '11424.png', '11472.png', '11516.png', '11532.png',
       '11538.png', '11588.png', '11594.png', '11598.png', '11612.png',
       '11622.png', '11625.png', '11652.png', '11654.png', '11678.png',
       '11680.png', '11681.png', '11689.png', '11715.png', '11718.png',
       '11770.png', '11773.png', '11782.png', '11897.png', '11916.png',
       '11932.png', '11947.png', '11951.png', '11988.png', '12012.png',
       '12015.png', '12045.png', '12051.png', '12069.png', '12096.png',
       '12104.png', '12128.png', '12136.png', '12142.png', '12155.png',
       '12180.png', '12213.png', '12269.png', '12279.png', '12287.png',
       '12302.png', '12303.png', '12327.png', '12332.png', '12346.png',
       '12364.png', '12383.png', '12399.png', '12453.png', '12461.png',
       '12474.png', '12492.png', '12541.png', '12565.png', '12581.png',
       '12589.png', '12601.png', '12630.png', '12640.png', '12642.png',
       '12688.png', '12691.png', '12695.png', '12710.png', '12754.png',
       '12785.png', '12789.png', '12818.png', '12819.png', '12832.png',
       '12844.png', '12857.png', '12876.png', '12896.png', '12912.png',
       '12918.png', '12930.png', '12931.png', '12964.png', '12980.png',
       '12998.png', '12999.png', '13006.png', '13021.png', '13023.png',
       '13051.png', '13058.png', '13066.png', '13072.png', '13082.png',
       '13098.png', '13111.png', '13119.png', '13129.png', '13181.png',
       '13192.png', '13197.png', '13202.png', '13207.png', '13213.png',
       '13219.png', '13246.png', '13289.png', '13291.png', '13297.png',
       '13306.png', '13315.png', '13317.png', '13327.png', '13330.png',
       '13336.png', '13342.png', '13350.png', '13353.png', '13357.png',
       '13362.png', '13372.png', '13374.png', '13388.png', '13393.png',
       '13409.png', '13459.png', '13464.png', '13521.png', '13527.png',
       '13565.png', '13575.png', '13614.png', '13623.png', '13636.png',
       '13649.png', '13652.png', '13660.png', '13661.png', '13668.png',
       '13670.png', '13717.png', '13718.png', '13751.png', '13768.png',
       '13771.png', '13772.png', '13775.png', '13799.png', '13807.png',
       '13853.png', '13857.png', '13866.png', '13880.png', '13892.png',
       '13898.png', '13909.png', '13931.png', '13936.png', '13944.png',
       '13953.png', '13966.png', '13971.png', '13973.png', '13988.png',
       '14000.png', '14020.png', '14027.png', '14028.png', '14038.png',
       '14039.png', '14065.png', '14093.png', '14099.png', '14147.png',
       '14184.png', '14193.png', '14202.png', '14204.png', '14224.png',
       '14230.png', '14250.png', '14255.png'], dtype=object)

In [19]:
# toothbrush의 file name list화
toothbrush = df.loc[df['class']=='toothbrush', ['file_name']]['file_name'].values
toothbrush

array(['10029.png', '10116.png', '10119.png', '10176.png', '10202.png',
       '10237.png', '10268.png', '10320.png', '10439.png', '10540.png',
       '10573.png', '10601.png', '10629.png', '10654.png', '10818.png',
       '10828.png', '10843.png', '11056.png', '11080.png', '11202.png',
       '11218.png', '11231.png', '11243.png', '11261.png', '11458.png',
       '11541.png', '11593.png', '11596.png', '11602.png', '11708.png',
       '11711.png', '11743.png', '11750.png', '11873.png', '11913.png',
       '12009.png', '12058.png', '12159.png', '12163.png', '12321.png',
       '12366.png', '12480.png', '12551.png', '12596.png', '12599.png',
       '12613.png', '12636.png', '12685.png', '12794.png', '12840.png',
       '12873.png', '12884.png', '12925.png', '12955.png', '12981.png',
       '12993.png', '13028.png', '13127.png', '13134.png', '13155.png',
       '13168.png', '13245.png', '13256.png', '13443.png', '13583.png',
       '13618.png', '13675.png', '13699.png', '13851.png', '13914.png',
       '13920.png', '13933.png', '14053.png', '14062.png', '14196.png'],
      dtype=object)

In [20]:
# transistor의 file name list화
transistor = df.loc[df['class']=='transistor', ['file_name']]['file_name'].values
transistor

array(['10000.png', '10002.png', '10009.png', '10042.png', '10049.png',
       '10072.png', '10091.png', '10097.png', '10135.png', '10138.png',
       '10140.png', '10143.png', '10144.png', '10146.png', '10199.png',
       '10216.png', '10283.png', '10290.png', '10296.png', '10366.png',
       '10377.png', '10384.png', '10391.png', '10392.png', '10412.png',
       '10435.png', '10449.png', '10451.png', '10488.png', '10545.png',
       '10551.png', '10575.png', '10578.png', '10583.png', '10595.png',
       '10669.png', '10672.png', '10716.png', '10733.png', '10760.png',
       '10781.png', '10789.png', '10801.png', '10821.png', '10824.png',
       '10854.png', '10879.png', '10908.png', '10915.png', '10923.png',
       '10975.png', '10992.png', '11017.png', '11041.png', '11057.png',
       '11070.png', '11075.png', '11111.png', '11122.png', '11146.png',
       '11153.png', '11156.png', '11188.png', '11200.png', '11229.png',
       '11256.png', '11275.png', '11283.png', '11290.png', '11302.png',
       '11304.png', '11311.png', '11329.png', '11347.png', '11348.png',
       '11351.png', '11353.png', '11368.png', '11427.png', '11436.png',
       '11449.png', '11479.png', '11487.png', '11524.png', '11539.png',
       '11547.png', '11569.png', '11573.png', '11576.png', '11590.png',
       '11614.png', '11635.png', '11684.png', '11685.png', '11729.png',
       '11752.png', '11778.png', '11797.png', '11824.png', '11841.png',
       '11844.png', '11861.png', '11887.png', '11929.png', '11965.png',
       '12016.png', '12018.png', '12019.png', '12027.png', '12046.png',
       '12054.png', '12065.png', '12068.png', '12118.png', '12124.png',
       '12127.png', '12164.png', '12183.png', '12186.png', '12198.png',
       '12226.png', '12237.png', '12239.png', '12243.png', '12248.png',
       '12250.png', '12284.png', '12286.png', '12296.png', '12339.png',
       '12353.png', '12355.png', '12359.png', '12362.png', '12384.png',
       '12386.png', '12407.png', '12408.png', '12419.png', '12447.png',
       '12460.png', '12464.png', '12471.png', '12563.png', '12591.png',
       '12648.png', '12654.png', '12657.png', '12667.png', '12672.png',
       '12680.png', '12683.png', '12701.png', '12712.png', '12749.png',
       '12772.png', '12834.png', '12835.png', '12838.png', '12869.png',
       '12886.png', '12904.png', '12951.png', '12972.png', '12976.png',
       '12985.png', '13015.png', '13027.png', '13050.png', '13052.png',
       '13143.png', '13159.png', '13179.png', '13190.png', '13196.png',
       '13209.png', '13210.png', '13223.png', '13231.png', '13239.png',
       '13287.png', '13300.png', '13301.png', '13322.png', '13329.png',
       '13376.png', '13383.png', '13420.png', '13432.png', '13434.png',
       '13450.png', '13470.png', '13482.png', '13533.png', '13546.png',
       '13559.png', '13567.png', '13578.png', '13599.png', '13612.png',
       '13619.png', '13633.png', '13656.png', '13688.png', '13692.png',
       '13707.png', '13711.png', '13712.png', '13721.png', '13724.png',
       '13725.png', '13742.png', '13749.png', '13752.png', '13764.png',
       '13776.png', '13814.png', '13896.png', '13947.png', '13962.png',
       '13972.png', '13979.png', '14012.png', '14014.png', '14034.png',
       '14090.png', '14106.png', '14119.png', '14149.png', '14203.png',
       '14248.png', '14272.png', '14273.png'], dtype=object)

In [21]:
# wood의 file name list화
wood = df.loc[df['class']=='wood', ['file_name']]['file_name'].values
wood

array(['10003.png', '10005.png', '10012.png', '10015.png', '10017.png',
       '10027.png', '10030.png', '10040.png', '10043.png', '10048.png',
       '10052.png', '10059.png', '10061.png', '10088.png', '10192.png',
       '10193.png', '10196.png', '10241.png', '10251.png', '10252.png',
       '10261.png', '10266.png', '10321.png', '10325.png', '10341.png',
       '10357.png', '10362.png', '10364.png', '10379.png', '10396.png',
       '10399.png', '10404.png', '10415.png', '10430.png', '10434.png',
       '10441.png', '10457.png', '10484.png', '10530.png', '10553.png',
       '10561.png', '10570.png', '10577.png', '10619.png', '10622.png',
       '10635.png', '10638.png', '10684.png', '10692.png', '10723.png',
       '10730.png', '10756.png', '10793.png', '10798.png', '10799.png',
       '10800.png', '10826.png', '10832.png', '10841.png', '10859.png',
       '10863.png', '10870.png', '10885.png', '10893.png', '10949.png',
       '10952.png', '10959.png', '10993.png', '11010.png', '11047.png',
       '11064.png', '11134.png', '11137.png', '11191.png', '11199.png',
       '11227.png', '11247.png', '11253.png', '11257.png', '11281.png',
       '11291.png', '11296.png', '11357.png', '11362.png', '11363.png',
       '11369.png', '11374.png', '11378.png', '11400.png', '11407.png',
       '11416.png', '11426.png', '11428.png', '11435.png', '11460.png',
       '11484.png', '11495.png', '11518.png', '11551.png', '11554.png',
       '11601.png', '11608.png', '11615.png', '11639.png', '11657.png',
       '11658.png', '11661.png', '11667.png', '11698.png', '11702.png',
       '11723.png', '11739.png', '11749.png', '11795.png', '11833.png',
       '11850.png', '11852.png', '11860.png', '11936.png', '11962.png',
       '11967.png', '11981.png', '11994.png', '11995.png', '12013.png',
       '12033.png', '12039.png', '12043.png', '12073.png', '12083.png',
       '12106.png', '12117.png', '12119.png', '12122.png', '12133.png',
       '12134.png', '12162.png', '12170.png', '12178.png', '12184.png',
       '12199.png', '12203.png', '12224.png', '12235.png', '12240.png',
       '12255.png', '12264.png', '12292.png', '12298.png', '12313.png',
       '12379.png', '12403.png', '12463.png', '12469.png', '12482.png',
       '12500.png', '12501.png', '12508.png', '12510.png', '12520.png',
       '12525.png', '12532.png', '12547.png', '12549.png', '12554.png',
       '12558.png', '12564.png', '12605.png', '12608.png', '12610.png',
       '12616.png', '12621.png', '12623.png', '12634.png', '12644.png',
       '12686.png', '12728.png', '12745.png', '12747.png', '12748.png',
       '12760.png', '12771.png', '12779.png', '12784.png', '12804.png',
       '12812.png', '12831.png', '12858.png', '12863.png', '12874.png',
       '12880.png', '12927.png', '12936.png', '12945.png', '12961.png',
       '12996.png', '13034.png', '13035.png', '13041.png', '13047.png',
       '13074.png', '13095.png', '13115.png', '13139.png', '13156.png',
       '13171.png', '13183.png', '13203.png', '13224.png', '13226.png',
       '13259.png', '13265.png', '13277.png', '13295.png', '13319.png',
       '13321.png', '13370.png', '13373.png', '13399.png', '13412.png',
       '13417.png', '13428.png', '13435.png', '13441.png', '13453.png',
       '13491.png', '13505.png', '13554.png', '13589.png', '13594.png',
       '13598.png', '13615.png', '13616.png', '13625.png', '13626.png',
       '13638.png', '13667.png', '13746.png', '13757.png', '13760.png',
       '13770.png', '13787.png', '13789.png', '13864.png', '13871.png',
       '13875.png', '13877.png', '13882.png', '13899.png', '13922.png',
       '13929.png', '13941.png', '13943.png', '13949.png', '13970.png',
       '13996.png', '14049.png', '14069.png', '14102.png', '14108.png',
       '14110.png', '14121.png', '14128.png', '14137.png', '14159.png',
       '14160.png', '14162.png', '14170.png', '14176.png', '14186.png',
       '14191.png', '14208.png', '14226.png', '14227.png', '14232.png',
       '14254.png', '14259.png', '14270.png'], dtype=object)

In [22]:
# zipper의 file name list화
zipper = df.loc[df['class']=='zipper', ['file_name']]['file_name'].values
zipper

array(['10020.png', '10036.png', '10063.png', '10071.png', '10073.png',
       '10078.png', '10081.png', '10098.png', '10112.png', '10128.png',
       '10131.png', '10148.png', '10153.png', '10174.png', '10182.png',
       '10194.png', '10212.png', '10228.png', '10235.png', '10236.png',
       '10259.png', '10289.png', '10337.png', '10340.png', '10352.png',
       '10361.png', '10371.png', '10372.png', '10419.png', '10426.png',
       '10437.png', '10445.png', '10478.png', '10480.png', '10486.png',
       '10514.png', '10537.png', '10544.png', '10554.png', '10557.png',
       '10567.png', '10600.png', '10605.png', '10639.png', '10659.png',
       '10666.png', '10683.png', '10698.png', '10699.png', '10700.png',
       '10702.png', '10715.png', '10726.png', '10729.png', '10741.png',
       '10750.png', '10753.png', '10757.png', '10763.png', '10774.png',
       '10775.png', '10802.png', '10811.png', '10834.png', '10849.png',
       '10861.png', '10872.png', '10887.png', '10894.png', '10899.png',
       '10902.png', '10917.png', '10925.png', '10934.png', '10950.png',
       '10995.png', '11006.png', '11007.png', '11053.png', '11059.png',
       '11060.png', '11077.png', '11082.png', '11102.png', '11120.png',
       '11136.png', '11161.png', '11176.png', '11187.png', '11190.png',
       '11197.png', '11198.png', '11204.png', '11214.png', '11221.png',
       '11248.png', '11264.png', '11341.png', '11346.png', '11358.png',
       '11383.png', '11403.png', '11420.png', '11430.png', '11455.png',
       '11456.png', '11459.png', '11466.png', '11473.png', '11474.png',
       '11486.png', '11496.png', '11499.png', '11534.png', '11536.png',
       '11555.png', '11582.png', '11600.png', '11634.png', '11662.png',
       '11675.png', '11693.png', '11700.png', '11709.png', '11713.png',
       '11721.png', '11730.png', '11731.png', '11753.png', '11759.png',
       '11790.png', '11806.png', '11834.png', '11839.png', '11853.png',
       '11854.png', '11855.png', '11878.png', '11889.png', '11896.png',
       '11906.png', '11911.png', '11915.png', '11917.png', '11941.png',
       '11974.png', '11982.png', '11986.png', '11992.png', '12000.png',
       '12026.png', '12031.png', '12035.png', '12036.png', '12040.png',
       '12048.png', '12060.png', '12087.png', '12095.png', '12097.png',
       '12099.png', '12105.png', '12108.png', '12115.png', '12143.png',
       '12149.png', '12188.png', '12191.png', '12207.png', '12232.png',
       '12241.png', '12252.png', '12290.png', '12295.png', '12330.png',
       '12338.png', '12345.png', '12350.png', '12352.png', '12374.png',
       '12395.png', '12398.png', '12427.png', '12436.png', '12450.png',
       '12466.png', '12475.png', '12476.png', '12528.png', '12539.png',
       '12556.png', '12575.png', '12587.png', '12590.png', '12637.png',
       '12649.png', '12658.png', '12674.png', '12704.png', '12733.png',
       '12773.png', '12796.png', '12801.png', '12805.png', '12807.png',
       '12814.png', '12821.png', '12847.png', '12885.png', '12908.png',
       '12913.png', '12932.png', '12934.png', '12938.png', '12944.png',
       '12958.png', '12987.png', '12997.png', '13003.png', '13017.png',
       '13029.png', '13037.png', '13048.png', '13049.png', '13084.png',
       '13187.png', '13194.png', '13212.png', '13220.png', '13228.png',
       '13248.png', '13274.png', '13280.png', '13281.png', '13290.png',
       '13292.png', '13302.png', '13325.png', '13328.png', '13331.png',
       '13335.png', '13347.png', '13359.png', '13381.png', '13389.png',
       '13390.png', '13391.png', '13405.png', '13416.png', '13457.png',
       '13475.png', '13498.png', '13511.png', '13580.png', '13584.png',
       '13586.png', '13593.png', '13595.png', '13600.png', '13640.png',
       '13647.png', '13671.png', '13731.png', '13767.png', '13773.png',
       '13780.png', '13782.png', '13806.png', '13824.png', '13827.png',
       '13839.png', '13863.png', '13878.png', '13884.png', '13923.png',
       '13991.png', '13995.png', '14011.png', '14046.png', '14061.png',
       '14064.png', '14070.png', '14081.png', '14085.png', '14109.png',
       '14120.png', '14123.png', '14168.png', '14171.png', '14178.png',
       '14188.png', '14195.png', '14197.png', '14205.png', '14211.png',
       '14215.png', '14240.png', '14242.png', '14243.png', '14244.png',
       '14275.png'], dtype=object)

### **각 class에 해당하는 img 분류**

In [23]:
path = './train/'
file_list = os.listdir(path)

file_list.sort()
print('train datasets :', len(file_list))

train datasets : 4277

In [24]:
# bottle 분류
for i in bottle:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/bottle/')

10004.png
10026.png
10053.png
10058.png
10060.png
10094.png
10159.png
10172.png
10204.png
10207.png
10217.png
10221.png
10240.png
10244.png
10248.png
10257.png
10260.png
10262.png
10308.png
10355.png
10375.png
10382.png
10385.png
10401.png
10403.png
10447.png
10458.png
10474.png
10482.png
10520.png
10524.png
10542.png
10552.png
10566.png
10569.png
10574.png
10580.png
10581.png
10584.png
10645.png
10653.png
10674.png
10681.png
10701.png
10712.png
10744.png
10751.png
10759.png
10767.png
10772.png
10779.png
10784.png
10792.png
10794.png
10827.png
10837.png
10839.png
10871.png
10875.png
10898.png
10912.png
10913.png
10916.png
10938.png
10968.png
10991.png
11018.png
11022.png
11023.png
11030.png
11051.png
11083.png
11133.png
11140.png
11143.png
11170.png
11252.png
11273.png
11295.png
11307.png
11310.png
11323.png
11332.png
11338.png
11352.png
11389.png
11401.png
11463.png
11559.png
11575.png
11628.png
11629.png
11642.png
11647.png
11649.png
11664.png
11683.png
11716.png
11728.png
11734.png
11735.png
11741.png
11755.png
11763.png
11791.png
11796.png
11799.png
11804.png
11805.png
11815.png
11828.png
11837.png
11840.png
11866.png
11875.png
11876.png
11885.png
11894.png
11905.png
11907.png
11912.png
11949.png
11961.png
11971.png
11973.png
11989.png
11990.png
12005.png
12006.png
12020.png
12030.png
12059.png
12152.png
12157.png
12166.png
12169.png
12171.png
12185.png
12187.png
12193.png
12196.png
12211.png
12214.png
12253.png
12254.png
12276.png
12277.png
12278.png
12281.png
12370.png
12401.png
12404.png
12444.png
12519.png
12553.png
12577.png
12584.png
12646.png
12655.png
12656.png
12671.png
12676.png
12706.png
12757.png
12758.png
12769.png
12786.png
12787.png
12817.png
12902.png
12910.png
12940.png
12962.png
12965.png
12973.png
12982.png
12986.png
12988.png
13032.png
13059.png
13063.png
13086.png
13100.png
13108.png
13112.png
13113.png
13126.png
13152.png
13241.png
13268.png
13271.png
13279.png
13286.png
13309.png
13334.png
13424.png
13436.png
13456.png
13458.png
13462.png
13466.png
13476.png
13506.png
13509.png
13528.png
13529.png
13531.png
13538.png
13541.png
13561.png
13581.png
13588.png
13679.png
13696.png
13698.png
13714.png
13716.png
13758.png
13763.png
13781.png
13786.png
13794.png
13834.png
13872.png
13874.png
13893.png
13969.png
13976.png
13981.png
14002.png
14031.png
14042.png
14089.png
14100.png
14139.png
14158.png
14174.png
14179.png
14200.png
14236.png
14271.png