<a href="https://colab.research.google.com/github/dodamhaee/CV-anomaly-detection-algorithm/blob/main/classify_img.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import os
import shutil
import pandas as pd

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
%cd drive/MyDrive/Dacon

/content/drive/MyDrive/Dacon

In [163]:
data = pd.read_csv('train_df.csv')



---


## **각 class에 해당하는 state의 csv 생성**


---

In [164]:
State = data.copy()
State = data[['class', 'state', 'file_name']]
State

           class state  file_name
0     transistor  good  10000.png
1        capsule  good  10001.png
2     transistor  good  10002.png
3           wood  good  10003.png
4         bottle  good  10004.png
...          ...   ...        ...
4272  transistor  good  14272.png
4273  transistor  good  14273.png
4274        grid  good  14274.png
4275      zipper  good  14275.png
4276       screw  good  14276.png

[4277 rows x 3 columns]

In [ ]:
# State.to_csv('state.csv', index=False)



---


## **각 class에 해당하는 file name들의 list 생성**


---

In [168]:
df = data[['class', 'file_name']].sort_values(['class', 'file_name'])
df

       class  file_name
4     bottle  10004.png
26    bottle  10026.png
53    bottle  10053.png
58    bottle  10058.png
60    bottle  10060.png
...      ...        ...
4240  zipper  14240.png
4242  zipper  14242.png
4243  zipper  14243.png
4244  zipper  14244.png
4275  zipper  14275.png

[4277 rows x 2 columns]

In [166]:
bottle = df.loc[df['class'] == 'bottle', ['file_name']]['file_name'].values
cable = df.loc[df['class'] == 'cable', ['file_name']]['file_name'].values
capsule = df.loc[df['class'] == 'capsule', ['file_name']]['file_name'].values
carpet = df.loc[df['class'] == 'carpet', ['file_name']]['file_name'].values
grid = df.loc[df['class'] == 'grid', ['file_name']]['file_name'].values
hazelnut = df.loc[df['class'] == 'hazelnut', ['file_name']]['file_name'].values
leather = df.loc[df['class'] == 'leather', ['file_name']]['file_name'].values
metalNut = df.loc[df['class']=='metal_nut', ['file_name']]['file_name'].values
pill = df.loc[df['class']=='pill', ['file_name']]['file_name'].values
screw = df.loc[df['class']=='screw', ['file_name']]['file_name'].values
tile = df.loc[df['class']=='tile', ['file_name']]['file_name'].values
toothbrush = df.loc[df['class']=='toothbrush', ['file_name']]['file_name'].values
transistor = df.loc[df['class']=='transistor', ['file_name']]['file_name'].values
wood = df.loc[df['class']=='wood', ['file_name']]['file_name'].values
zipper = df.loc[df['class']=='zipper', ['file_name']]['file_name'].values

In [ ]:
path = './train/'
fileList = os.listdir(path)

fileList.sort()
print('train datasets :', len(fileList))

In [ ]:
classList = [bottle, cable, capsule, carpet, grid, hazelnut, leather, metalNut, 
    pill, screw, tile, toothbrush, transistor, wood, zipper]
for i in fileList:
  idx=0
  for j in classList:
    if i>j: continue 
    if i in j:
      print(i)
      shutil.move(path + i, './classes/' + classList[idx])
      idx+=1



---


## **각 state에 해당하는 img 분류**


---

In [ ]:
State

       class           state  file_name
204   bottle    broken_large  10204.png
260   bottle    broken_large  10260.png
712   bottle    broken_large  10712.png
839   bottle    broken_large  10839.png
912   bottle    broken_large  10912.png
...      ...             ...        ...
1496  zipper  squeezed_teeth  11496.png
1700  zipper  squeezed_teeth  11700.png
3187  zipper  squeezed_teeth  13187.png
3647  zipper  squeezed_teeth  13647.png
3731  zipper  squeezed_teeth  13731.png

[4277 rows x 3 columns]

In [128]:
grouped = State.groupby(State['class'])['state'].unique()
grouped

class
bottle        [broken_large, broken_small, contamination, good]
cable         [bent_wire, cable_swap, combined, cut_inner_in...
capsule       [crack, faulty_imprint, good, poke, scratch, s...
carpet        [color, cut, good, hole, metal_contamination, ...
grid          [bent, broken, glue, good, metal_contamination...
hazelnut                        [crack, cut, good, hole, print]
leather                    [color, cut, fold, glue, good, poke]
metal_nut                    [bent, color, flip, good, scratch]
pill          [color, combined, contamination, crack, faulty...
screw         [good, manipulated_front, scratch_head, scratc...
tile          [crack, glue_strip, good, gray_stroke, oil, ro...
toothbrush                                    [defective, good]
transistor    [bent_lead, cut_lead, damaged_case, good, misp...
wood             [color, combined, good, hole, liquid, scratch]
zipper        [broken_teeth, combined, fabric_border, fabric...
Name: state, dtype: object

### bottle의 state img 분류

In [ ]:
!mkdir ./states/bottle/broken_large
!mkdir ./states/bottle/broken_small
!mkdir ./states/bottle/contamination
!mkdir ./states/bottle/good

In [169]:
bottle_brokenLarge = State.loc[(State['class']=='bottle') & (State['state']=='broken_large'), ['file_name']]['file_name'].values
bottle_brokenSmall = State.loc[(State['class']=='bottle') & (State['state']=='broken_small'), ['file_name']]['file_name'].values
bottle_contamination = State.loc[(State['class']=='bottle') & (State['state']=='contamination'), ['file_name']]['file_name'].values
bottle_good = State.loc[(State['class']=='bottle') & (State['state']=='good'), ['file_name']]['file_name'].values

In [ ]:
for i in bottle:
  idx=0
  for j in [bottle_brokenLarge, bottle_brokenSmall, bottle_contamination, bottle_good]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/bottle/' + i, './states/bottle/' + grouped[0][idx])
    idx+=1

###cable의 state img 분류

In [ ]:
!mkdir ./states/cable/bent_wire
!mkdir ./states/cable/cable_swap
!mkdir ./states/cable/combined
!mkdir ./states/cable/cut_inner_insulation
!mkdir ./states/cable/cut_outer_insulation
!mkdir ./states/cable/good
!mkdir ./states/cable/missing_cable
!mkdir ./states/cable/missing_wire
!mkdir ./states/cable/poke_insulation

In [138]:
cable_bentWire = State.loc[(State['class']=='cable') & (State['state']=='bent_wire'), ['file_name']]['file_name'].values
cable_cableSwap = State.loc[(State['class']=='cable') & (State['state']=='cable_swap'), ['file_name']]['file_name'].values
cable_combined = State.loc[(State['class']=='cable') & (State['state']=='combined'), ['file_name']]['file_name'].values
cable_cutInnerInsulation = State.loc[(State['class']=='cable') & (State['state']=='cut_inner_insulation'), ['file_name']]['file_name'].values
cable_cutOuterInsulation = State.loc[(State['class']=='cable') & (State['state']=='cut_outer_insulation'), ['file_name']]['file_name'].values
cable_good = State.loc[(State['class']=='cable') & (State['state']=='good'), ['file_name']]['file_name'].values
cable_missingCable = State.loc[(State['class']=='cable') & (State['state']=='missing_cable'), ['file_name']]['file_name'].values
cable_missingWire = State.loc[(State['class']=='cable') & (State['state']=='missing_wire'), ['file_name']]['file_name'].values
cable_pokeInsulation = State.loc[(State['class']=='cable') & (State['state']=='poke_insulation'), ['file_name']]['file_name'].values

In [ ]:
for i in cable:
  idx=0
  for j in [cable_bentWire, cable_cableSwap, cable_combined,
            cable_cutInnerInsulation, cable_cutOuterInsulation, cable_good,
            cable_missingCable, cable_missingWire, cable_pokeInsulation]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/cable/' + i, './states/cable/' + grouped[1][idx])
    idx+=1

###capsule의 state img 분류

In [ ]:
!mkdir ./states/capsule/crack
!mkdir ./states/capsule/faulty_imprint
!mkdir ./states/capsule/good
!mkdir ./states/capsule/poke
!mkdir ./states/capsule/scratch
!mkdir ./states/capsule/squeeze

In [140]:
capsule_crack = State.loc[(State['class']=='capsule') & (State['state']=='crack'), ['file_name']]['file_name'].values
capsule_faultyImprint = State.loc[(State['class']=='capsule') & (State['state']=='faulty_imprint'), ['file_name']]['file_name'].values
capsule_good = State.loc[(State['class']=='capsule') & (State['state']=='good'), ['file_name']]['file_name'].values
capsule_poke = State.loc[(State['class']=='capsule') & (State['state']=='poke'), ['file_name']]['file_name'].values
capsule_scratch = State.loc[(State['class']=='capsule') & (State['state']=='scratch'), ['file_name']]['file_name'].values
capsule_squeeze = State.loc[(State['class']=='capsule') & (State['state']=='squeeze'), ['file_name']]['file_name'].values

In [ ]:
for i in capsule:
  idx=0
  for j in [capsule_crack, capsule_faultyImprint, capsule_good, capsule_poke, capsule_scratch, capsule_squeeze]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/capsule/' + i, './states/capsule/' + grouped[2][idx])
    idx+=1

###carpet의 state img 분류

In [ ]:
!mkdir ./states/carpet/crack
!mkdir ./states/carpet/faulty_imprint
!mkdir ./states/carpet/good
!mkdir ./states/carpet/poke
!mkdir ./states/carpet/scratch
!mkdir ./states/carpet/squeeze

In [148]:
carpet_color = State.loc[(State['class']=='capsule') & (State['state']=='color'), ['file_name']]['file_name'].values
carpet_cut = State.loc[(State['class']=='capsule') & (State['state']=='cut'), ['file_name']]['file_name'].values
carpet_good = State.loc[(State['class']=='capsule') & (State['state']=='good'), ['file_name']]['file_name'].values
carpet_hole = State.loc[(State['class']=='capsule') & (State['state']=='hole'), ['file_name']]['file_name'].values
carpet_metalContamination = State.loc[(State['class']=='capsule') & (State['state']=='metal_contamination'), ['file_name']]['file_name'].values
carpet_thread = State.loc[(State['class']=='capsule') & (State['state']=='thread'), ['file_name']]['file_name'].values

In [ ]:
for i in carpet:
  idx=0
  for j in [carpet_color, carpet_cut, carpet_good, carpet_hole, carpet_metalContamination, carpet_thread]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/carpet/' + i, './states/carpet/' + grouped[3][idx])
    idx+=1

###grid의 state img 분류

In [ ]:
!mkdir ./states/grid/bent
!mkdir ./states/grid/broken
!mkdir ./states/grid/glue
!mkdir ./states/grid/good
!mkdir ./states/grid/metal_contamination
!mkdir ./states/grid/thread

In [150]:
grid_bent = State.loc[(State['class']=='grid') & (State['state']=='bent'), ['file_name']]['file_name'].values
grid_broken = State.loc[(State['class']=='grid') & (State['state']=='broken'), ['file_name']]['file_name'].values
grid_glue = State.loc[(State['class']=='grid') & (State['state']=='glue'), ['file_name']]['file_name'].values
grid_good = State.loc[(State['class']=='grid') & (State['state']=='good'), ['file_name']]['file_name'].values
grid_metalContamination = State.loc[(State['class']=='grid') & (State['state']=='metal_contamination'), ['file_name']]['file_name'].values
grid_thread = State.loc[(State['class']=='grid') & (State['state']=='thread'), ['file_name']]['file_name'].values

In [ ]:
for i in grid:
  idx=0
  for j in [grid_bent, grid_broken, grid_glue, grid_good, grid_metalContamination, grid_thread]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/grid/' + i, './states/grid/' + grouped[4][idx])
    idx+=1

###hazelnut의 state img 분류

In [ ]:
!mkdir ./states/hazelnut/crack
!mkdir ./states/hazelnut/cut
!mkdir ./states/hazelnut/good
!mkdir ./states/hazelnut/hole
!mkdir ./states/hazelnut/print

In [151]:
hazelnut_crack = State.loc[(State['class']=='hazelnut') & (State['state']=='crack'), ['file_name']]['file_name'].values
hazelnut_cut = State.loc[(State['class']=='hazelnut') & (State['state']=='cut'), ['file_name']]['file_name'].values
hazelnut_good = State.loc[(State['class']=='hazelnut') & (State['state']=='good'), ['file_name']]['file_name'].values
hazelnut_hole = State.loc[(State['class']=='hazelnut') & (State['state']=='hole'), ['file_name']]['file_name'].values
hazelnut_print = State.loc[(State['class']=='hazelnut') & (State['state']=='print'), ['file_name']]['file_name'].values

In [ ]:
for i in hazelnut:
  idx=0
  for j in [hazelnut_crack, hazelnut_cut, hazelnut_good, hazelnut_hole, hazelnut_print]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/hazelnut/' + i, './states/hazelnut/' + grouped[5][idx])
    idx+=1

###leather의 state img 분류

In [ ]:
!mkdir ./states/leather/color
!mkdir ./states/leather/cut
!mkdir ./states/leather/fold
!mkdir ./states/leather/glue
!mkdir ./states/leather/good
!mkdir ./states/leather/poke

In [154]:
leather_color = State.loc[(State['class']=='leather') & (State['state']=='color'), ['file_name']]['file_name'].values
leather_cut = State.loc[(State['class']=='leather') & (State['state']=='cut'), ['file_name']]['file_name'].values
leather_fold = State.loc[(State['class']=='leather') & (State['state']=='fold'), ['file_name']]['file_name'].values
leather_glue = State.loc[(State['class']=='leather') & (State['state']=='glue'), ['file_name']]['file_name'].values
leather_good = State.loc[(State['class']=='leather') & (State['state']=='good'), ['file_name']]['file_name'].values
leather_poke = State.loc[(State['class']=='leather') & (State['state']=='poke'), ['file_name']]['file_name'].values

In [ ]:
for i in leather:
  idx=0
  for j in [leather_color, leather_cut, leather_fold, leather_glue, leather_good, leather_poke]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/leather/' + i, './states/leather/' + grouped[6][idx])
    idx+=1

###metal_nut의 state img 분류

In [ ]:
!mkdir ./states/metal_nut/bent
!mkdir ./states/metal_nut/color
!mkdir ./states/metal_nut/flip
!mkdir ./states/metal_nut/good
!mkdir ./states/metal_nut/scratch

In [156]:
metalNut_bent = State.loc[(State['class']=='metal_nut') & (State['state']=='bent'), ['file_name']]['file_name'].values
metalNut_color = State.loc[(State['class']=='metal_nut') & (State['state']=='color'), ['file_name']]['file_name'].values
metalNut_flip = State.loc[(State['class']=='metal_nut') & (State['state']=='flip'), ['file_name']]['file_name'].values
metalNut_good = State.loc[(State['class']=='metal_nut') & (State['state']=='good'), ['file_name']]['file_name'].values
metalNut_scratch = State.loc[(State['class']=='metal_nut') & (State['state']=='scratch'), ['file_name']]['file_name'].values

In [ ]:
for i in metalNut:
  idx=0
  for j in [metalNut_bent, metalNut_color, metalNut_flip, metalNut_good, metalNut_scratch]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/metal_nut/' + i, './states/metal_nut/' + grouped[6][idx])
    idx+=1

###pill의 state img 분류

In [ ]:
!mkdir ./states/pill/color
!mkdir ./states/pill/combined
!mkdir ./states/pill/contamination
!mkdir ./states/pill/crack
!mkdir ./states/pill/faulty_imprint
!mkdir ./states/pill/good
!mkdir ./states/pill/pill_type
!mkdir ./states/pill/scratch

In [177]:
pill_color = State.loc[(State['class']=='pill') & (State['state']=='color'), ['file_name']]['file_name'].values
pill_combined = State.loc[(State['class']=='pill') & (State['state']=='combined'), ['file_name']]['file_name'].values
pill_contamination = State.loc[(State['class']=='pill') & (State['state']=='contamination'), ['file_name']]['file_name'].values
pill_crack = State.loc[(State['class']=='pill') & (State['state']=='crack'), ['file_name']]['file_name'].values
pill_faultyImprint = State.loc[(State['class']=='pill') & (State['state']=='faulty_imprint'), ['file_name']]['file_name'].values
pill_good = State.loc[(State['class']=='pill') & (State['state']=='good'), ['file_name']]['file_name'].values
pill_pillType = State.loc[(State['class']=='pill') & (State['state']=='pill_type'), ['file_name']]['file_name'].values
pill_scratch = State.loc[(State['class']=='pill') & (State['state']=='scratch'), ['file_name']]['file_name'].values

In [ ]:
for i in pill:
  idx=0
  for j in [pill_color, pill_combined, pill_contamination, pill_crack,
            pill_faultyImprint, pill_good, pill_pillType, pill_scratch]:
    if i<j: continue
    if i in j:
      # print(i)
      shutil.move('./states/pill/' + i, './states/pill/' + grouped[7][idx])
    idx+=1

###screw의 state img 분류

In [ ]:
!mkdir ./states/screw/good
!mkdir ./states/screw/manipulated_front
!mkdir ./states/screw/scratch_head
!mkdir ./states/screw/scratch_neck
!mkdir ./states/screw/thread_side
!mkdir ./states/screw/thread_top

In [ ]:
screw_good = state.loc[(state['class']=='screw') & (state['state']=='good'), ['file_name']]['file_name'].values
screw_manipulatedFront = state.loc[(state['class']=='screw') & (state['state']=='manipulated_front'), ['file_name']]['file_name'].values
screw_scratchHead = state.loc[(state['class']=='screw') & (state['state']=='scratch_head'), ['file_name']]['file_name'].values
screw_scratchNeck = state.loc[(state['class']=='screw') & (state['state']=='scratch_neck'), ['file_name']]['file_name'].values
screw_threadSide = state.loc[(state['class']=='screw') & (state['state']=='thread_side'), ['file_name']]['file_name'].values
screw_threadTop = state.loc[(state['class']=='screw') & (state['state']=='thread_top'), ['file_name']]['file_name'].values

In [ ]:
# screw - good
for i in screw_good:
  for j in screw:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/screw/' + i, './states/screw/good/')

In [ ]:
# screw - manipulated_front
for i in screw_manipulatedFront:
  for j in screw:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/screw/' + i, './states/screw/manipulated_front/')

In [ ]:
# screw - scratch_head
for i in screw_scratchHead:
  for j in screw:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/screw/' + i, './states/screw/scratch_head/')

In [ ]:
# screw - scratch_neck
for i in screw_scratchNeck:
  for j in screw:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/screw/' + i, './states/screw/scratch_neck/')

In [ ]:
# screw - thread_side
for i in screw_threadSide:
  for j in screw:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/screw/' + i, './states/screw/thread_side/')

In [ ]:
# screw - thread_top
for i in screw_threadTop:
  for j in screw:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/screw/' + i, './states/screw/thread_top/')

###tile의 state img 분류

In [ ]:
!mkdir ./states/tile/crack
!mkdir ./states/tile/glue_strip
!mkdir ./states/tile/good
!mkdir ./states/tile/gray_stroke
!mkdir ./states/tile/oil
!mkdir ./states/tile/rough

In [ ]:
tile_crack = state.loc[(state['class']=='tile') & (state['state']=='crack'), ['file_name']]['file_name'].values
tile_glueStrip = state.loc[(state['class']=='tile') & (state['state']=='glue_strip'), ['file_name']]['file_name'].values
tile_good = state.loc[(state['class']=='tile') & (state['state']=='good'), ['file_name']]['file_name'].values
tile_grayStroke = state.loc[(state['class']=='tile') & (state['state']=='gray_stroke'), ['file_name']]['file_name'].values
tile_oil = state.loc[(state['class']=='tile') & (state['state']=='oil'), ['file_name']]['file_name'].values
tile_rough = state.loc[(state['class']=='tile') & (state['state']=='rough'), ['file_name']]['file_name'].values

In [ ]:
# tile - crack
for i in tile_crack:
  for j in tile:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/tile/' + i, './states/tile/crack/')

In [ ]:
# tile - glue_strip
for i in tile_glueStrip:
  for j in tile:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/tile/' + i, './states/tile/glue_strip/')

In [ ]:
# tile - good
for i in tile_good:
  for j in tile:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/tile/' + i, './states/tile/good/')

In [ ]:
# tile - gray_stroke
for i in tile_grayStroke:
  for j in tile:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/tile/' + i, './states/tile/gray_stroke/')

In [ ]:
# tile - oil
for i in tile_oil:
  for j in tile:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/tile/' + i, './states/tile/oil/')

In [ ]:
# tile - rough
for i in tile_rough:
  for j in tile:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/tile/' + i, './states/tile/rough/')

###toothbrush의 state img 분류

In [55]:
!mkdir ./states/toothbrush/defective
!mkdir ./states/toothbrush/good

In [61]:
toothbrush_defective = state.loc[(state['class']=='toothbrush') & (state['state']=='defective'), ['file_name']]['file_name'].values
toothbrush_good = state.loc[(state['class']=='toothbrush') & (state['state']=='good'), ['file_name']]['file_name'].values

In [62]:
# toothbrush - defective
for i in toothbrush_defective:
  for j in toothbrush:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/toothbrush/' + i, './states/toothbrush/defective/')

10237.png
10573.png
11080.png
11218.png
11231.png
11750.png
12159.png
12163.png
12321.png
12873.png
12925.png
12955.png
13134.png
13245.png
14053.png

In [64]:
# toothbrush - good
for i in toothbrush_good:
  for j in toothbrush:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/toothbrush/' + i, './states/toothbrush/good/')

10029.png
10116.png
10119.png
10176.png
10202.png
10268.png
10320.png
10439.png
10540.png
10601.png
10629.png
10654.png
10818.png
10828.png
10843.png
11056.png
11202.png
11243.png
11261.png
11458.png
11541.png
11593.png
11596.png
11602.png
11708.png
11711.png
11743.png
11873.png
11913.png
12009.png
12058.png
12366.png
12480.png
12551.png
12596.png
12599.png
12613.png
12636.png
12685.png
12794.png
12840.png
12884.png
12981.png
12993.png
13028.png
13127.png
13155.png
13168.png
13256.png
13443.png
13583.png
13618.png
13675.png
13699.png
13851.png
13914.png
13920.png
13933.png
14062.png
14196.png

###transistor의 state img 분류

In [65]:
!mkdir ./states/transistor/bent_lead
!mkdir ./states/transistor/cut_lead
!mkdir ./states/transistor/damaged_case
!mkdir ./states/transistor/good
!mkdir ./states/transistor/misplaced

In [66]:
transistor_bentLead = state.loc[(state['class']=='transistor') & (state['state']=='bent_lead'), ['file_name']]['file_name'].values
transistor_cutLead = state.loc[(state['class']=='transistor') & (state['state']=='cut_lead'), ['file_name']]['file_name'].values
transistor_damagedCase = state.loc[(state['class']=='transistor') & (state['state']=='damaged_case'), ['file_name']]['file_name'].values
transistor_good = state.loc[(state['class']=='transistor') & (state['state']=='good'), ['file_name']]['file_name'].values
transistor_misplaced = state.loc[(state['class']=='transistor') & (state['state']=='misplaced'), ['file_name']]['file_name'].values

In [67]:
# transistor - bent_lead
for i in transistor_bentLead:
  for j in transistor:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/transistor/' + i, './states/transistor/bent_lead/')

10144.png
12353.png
12355.png
13752.png
14248.png

In [68]:
# transistor - cut_lead
for i in transistor_cutLead:
  for j in transistor:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/transistor/' + i, './states/transistor/cut_lead/')

11449.png
12904.png
13015.png
13159.png
13776.png

In [69]:
# transistor - damaged_case
for i in transistor_damagedCase:
  for j in transistor:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/transistor/' + i, './states/transistor/damaged_case/')

10392.png
11479.png
11569.png
12016.png
12384.png

In [70]:
# transistor - good
for i in transistor_good:
  for j in transistor:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/transistor/' + i, './states/transistor/good/')

10000.png
10002.png
10009.png
10042.png
10049.png
10072.png
10091.png
10097.png
10135.png
10138.png
10140.png
10143.png
10146.png
10199.png
10216.png
10283.png
10290.png
10296.png
10366.png
10377.png
10384.png
10391.png
10412.png
10435.png
10449.png
10451.png
10488.png
10545.png
10551.png
10575.png
10578.png
10583.png
10595.png
10669.png
10672.png
10716.png
10733.png
10760.png
10781.png
10789.png
10801.png
10821.png
10854.png
10879.png
10908.png
10915.png
10923.png
10975.png
10992.png
11041.png
11057.png
11070.png
11075.png
11111.png
11122.png
11146.png
11153.png
11156.png
11188.png
11200.png
11229.png
11256.png
11275.png
11283.png
11290.png
11302.png
11304.png
11311.png
11329.png
11347.png
11348.png
11351.png
11353.png
11368.png
11427.png
11436.png
11487.png
11524.png
11539.png
11547.png
11573.png
11576.png
11590.png
11614.png
11635.png
11684.png
11685.png
11729.png
11752.png
11778.png
11797.png
11824.png
11841.png
11844.png
11861.png
11887.png
11929.png
11965.png
12018.png
12019.png
12027.png
12046.png
12054.png
12065.png
12068.png
12118.png
12124.png
12127.png
12164.png
12183.png
12186.png
12198.png
12226.png
12237.png
12239.png
12243.png
12248.png
12250.png
12284.png
12286.png
12296.png
12339.png
12359.png
12362.png
12386.png
12407.png
12408.png
12419.png
12447.png
12460.png
12464.png
12563.png
12591.png
12648.png
12654.png
12657.png
12667.png
12672.png
12680.png
12683.png
12701.png
12712.png
12749.png
12772.png
12834.png
12835.png
12838.png
12869.png
12886.png
12951.png
12972.png
12976.png
12985.png
13027.png
13050.png
13052.png
13143.png
13179.png
13190.png
13196.png
13209.png
13210.png
13223.png
13231.png
13239.png
13287.png
13300.png
13301.png
13322.png
13329.png
13376.png
13383.png
13420.png
13432.png
13434.png
13450.png
13470.png
13482.png
13533.png
13546.png
13559.png
13567.png
13578.png
13599.png
13612.png
13619.png
13633.png
13656.png
13688.png
13692.png
13707.png
13711.png
13712.png
13721.png
13724.png
13725.png
13742.png
13749.png
13764.png
13814.png
13896.png
13947.png
13962.png
13972.png
13979.png
14012.png
14034.png
14090.png
14106.png
14119.png
14149.png
14272.png
14273.png

In [71]:
# transistor - misplaced
for i in transistor_misplaced:
  for j in transistor:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/transistor/' + i, './states/transistor/misplaced/')

10824.png
11017.png
12471.png
14014.png
14203.png

###wood의 state img 분류

In [72]:
!mkdir ./states/wood/color
!mkdir ./states/wood/combined
!mkdir ./states/wood/good
!mkdir ./states/wood/hole
!mkdir ./states/wood/liquid
!mkdir ./states/wood/scratch

In [73]:
wood_color = state.loc[(state['class']=='wood') & (state['state']=='color'), ['file_name']]['file_name'].values
wood_combined = state.loc[(state['class']=='wood') & (state['state']=='combined'), ['file_name']]['file_name'].values
wood_good = state.loc[(state['class']=='wood') & (state['state']=='good'), ['file_name']]['file_name'].values
wood_hole = state.loc[(state['class']=='wood') & (state['state']=='hole'), ['file_name']]['file_name'].values
wood_liquid = state.loc[(state['class']=='wood') & (state['state']=='liquid'), ['file_name']]['file_name'].values
wood_scratch = state.loc[(state['class']=='wood') & (state['state']=='scratch'), ['file_name']]['file_name'].values

In [74]:
# wood - color
for i in wood_color:
  for j in wood:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/wood/' + i, './states/wood/color/')

11134.png
11281.png
13321.png
13667.png

In [75]:
# wood - combined
for i in wood_combined:
  for j in wood:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/wood/' + i, './states/wood/combined/')

10088.png
12184.png
12482.png
12784.png
13074.png
13491.png

In [76]:
# wood - good
for i in wood_good:
  for j in wood:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/wood/' + i, './states/wood/good/')

10003.png
10005.png
10012.png
10015.png
10017.png
10027.png
10030.png
10040.png
10043.png
10048.png
10052.png
10059.png
10061.png
10192.png
10193.png
10196.png
10241.png
10251.png
10252.png
10261.png
10266.png
10321.png
10325.png
10341.png
10357.png
10362.png
10364.png
10379.png
10396.png
10399.png
10404.png
10415.png
10430.png
10434.png
10457.png
10484.png
10530.png
10553.png
10561.png
10570.png
10577.png
10619.png
10622.png
10638.png
10684.png
10692.png
10723.png
10730.png
10756.png
10793.png
10798.png
10799.png
10800.png
10826.png
10841.png
10859.png
10863.png
10870.png
10885.png
10893.png
10949.png
10952.png
10959.png
10993.png
11010.png
11047.png
11064.png
11137.png
11191.png
11199.png
11227.png
11247.png
11253.png
11257.png
11291.png
11296.png
11357.png
11362.png
11363.png
11369.png
11374.png
11378.png
11400.png
11407.png
11416.png
11426.png
11428.png
11435.png
11460.png
11484.png
11495.png
11518.png
11551.png
11554.png
11601.png
11608.png
11615.png
11639.png
11657.png
11661.png
11667.png
11698.png
11702.png
11723.png
11739.png
11749.png
11833.png
11850.png
11852.png
11860.png
11936.png
11962.png
11967.png
11981.png
11994.png
11995.png
12013.png
12033.png
12039.png
12043.png
12073.png
12117.png
12119.png
12122.png
12133.png
12134.png
12162.png
12170.png
12199.png
12203.png
12224.png
12235.png
12240.png
12255.png
12264.png
12292.png
12298.png
12379.png
12403.png
12463.png
12469.png
12501.png
12508.png
12520.png
12532.png
12547.png
12549.png
12554.png
12558.png
12564.png
12605.png
12608.png
12616.png
12621.png
12634.png
12644.png
12686.png
12728.png
12745.png
12747.png
12760.png
12771.png
12779.png
12804.png
12812.png
12831.png
12858.png
12863.png
12874.png
12880.png
12927.png
12936.png
12945.png
12961.png
12996.png
13034.png
13035.png
13041.png
13047.png
13095.png
13115.png
13139.png
13156.png
13171.png
13203.png
13224.png
13265.png
13277.png
13295.png
13319.png
13370.png
13373.png
13399.png
13412.png
13417.png
13428.png
13435.png
13441.png
13453.png
13554.png
13589.png
13594.png
13598.png
13615.png
13616.png
13625.png
13626.png
13638.png
13746.png
13757.png
13760.png
13770.png
13787.png
13789.png
13864.png
13871.png
13875.png
13877.png
13882.png
13899.png
13922.png
13929.png
13941.png
13943.png
13949.png
13970.png
13996.png
14049.png
14102.png
14108.png
14110.png
14121.png
14128.png
14137.png
14159.png
14160.png
14162.png
14170.png
14176.png
14186.png
14191.png
14226.png
14227.png
14232.png
14254.png
14259.png
14270.png

In [78]:
# wood - hole
for i in wood_hole:
  for j in wood:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/wood/' + i, './states/wood/hole/')

11795.png
12525.png
12748.png
13226.png
14069.png

In [79]:
# wood - liquid
for i in wood_liquid:
  for j in wood:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/wood/' + i, './states/wood/liquid/')

12106.png
12178.png
12610.png
13183.png
13259.png

In [80]:
# wood - scratch
for i in wood_scratch:
  for j in wood:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/wood/' + i, './states/wood/scratch/')

10441.png
10635.png
10832.png
11658.png
12083.png
12313.png
12500.png
12510.png
12623.png
13505.png
14208.png

###zipper의 state img 분류

In [81]:
!mkdir ./states/zipper/broken_teeth
!mkdir ./states/zipper/combined
!mkdir ./states/zipper/fabric_border
!mkdir ./states/zipper/fabric_interior
!mkdir ./states/zipper/good
!mkdir ./states/zipper/rough
!mkdir ./states/zipper/split_teeth
!mkdir ./states/zipper/squeezed_teeth

In [91]:
zipper_brokenTeeth = state.loc[(state['class']=='zipper') & (state['state']=='broken_teeth'), ['file_name']]['file_name'].values
zipper_combined = state.loc[(state['class']=='zipper') & (state['state']=='combined'), ['file_name']]['file_name'].values
zipper_fabricBorder = state.loc[(state['class']=='zipper') & (state['state']=='fabric_border'), ['file_name']]['file_name'].values
zipper_fabricInterior = state.loc[(state['class']=='zipper') & (state['state']=='fabric_interior'), ['file_name']]['file_name'].values
zipper_good = state.loc[(state['class']=='zipper') & (state['state']=='good'), ['file_name']]['file_name'].values
zipper_rough = state.loc[(state['class']=='zipper') & (state['state']=='rough'), ['file_name']]['file_name'].values
zipper_splitTeeth = state.loc[(state['class']=='zipper') & (state['state']=='split_teeth'), ['file_name']]['file_name'].values
zipper_squeezedTeeth = state.loc[(state['class']=='zipper') & (state['state']=='squeezed_teeth'), ['file_name']]['file_name'].values

In [83]:
# zipper - broken_teeth
for i in zipper_brokenTeeth:
  for j in zipper:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/zipper/' + i, './states/zipper/broken_teeth/')

10702.png
10757.png
10774.png
10849.png
11060.png
11198.png
12436.png
12450.png
13884.png
14085.png

In [84]:
# zipper - combined
for i in zipper_combined:
  for j in zipper:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/zipper/' + i, './states/zipper/combined/')

10537.png
10753.png
10802.png
11730.png
13475.png
13511.png
14070.png
14195.png

In [85]:
# zipper - fabric_border
for i in zipper_fabricBorder:
  for j in zipper:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/zipper/' + i, './states/zipper/fabric_border/')

10020.png
10861.png
13029.png
13302.png
13347.png
13389.png
13391.png
13498.png
14211.png

In [86]:
# zipper - fabric_interior
for i in zipper_fabricInterior:
  for j in zipper:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/zipper/' + i, './states/zipper/fabric_interior/')

10153.png
10182.png
10445.png
10478.png
11455.png
11600.png
12556.png
14205.png

In [87]:
# zipper - good
for i in zipper_good:
  for j in zipper:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/zipper/' + i, './states/zipper/good/')

10036.png
10063.png
10071.png
10078.png
10081.png
10098.png
10128.png
10131.png
10148.png
10174.png
10194.png
10212.png
10228.png
10236.png
10259.png
10289.png
10337.png
10340.png
10352.png
10361.png
10372.png
10419.png
10437.png
10480.png
10514.png
10544.png
10554.png
10567.png
10600.png
10639.png
10659.png
10666.png
10683.png
10698.png
10699.png
10700.png
10715.png
10729.png
10741.png
10750.png
10763.png
10775.png
10834.png
10872.png
10894.png
10899.png
10902.png
10917.png
10925.png
10934.png
10950.png
10995.png
11006.png
11007.png
11053.png
11059.png
11077.png
11082.png
11102.png
11120.png
11136.png
11161.png
11176.png
11187.png
11190.png
11197.png
11204.png
11214.png
11221.png
11248.png
11264.png
11341.png
11346.png
11358.png
11383.png
11403.png
11420.png
11459.png
11466.png
11473.png
11474.png
11486.png
11499.png
11534.png
11536.png
11555.png
11582.png
11634.png
11662.png
11675.png
11693.png
11709.png
11713.png
11721.png
11731.png
11753.png
11759.png
11790.png
11806.png
11834.png
11839.png
11853.png
11854.png
11855.png
11878.png
11889.png
11896.png
11906.png
11911.png
11915.png
11917.png
11941.png
11974.png
11982.png
11986.png
11992.png
12000.png
12026.png
12031.png
12035.png
12036.png
12040.png
12048.png
12060.png
12087.png
12095.png
12097.png
12099.png
12105.png
12108.png
12115.png
12143.png
12149.png
12188.png
12191.png
12207.png
12232.png
12241.png
12252.png
12290.png
12295.png
12330.png
12338.png
12345.png
12350.png
12352.png
12395.png
12398.png
12427.png
12466.png
12475.png
12476.png
12528.png
12539.png
12575.png
12590.png
12637.png
12649.png
12658.png
12674.png
12733.png
12773.png
12796.png
12801.png
12805.png
12807.png
12814.png
12821.png
12847.png
12885.png
12908.png
12913.png
12932.png
12934.png
12938.png
12944.png
12958.png
12987.png
12997.png
13003.png
13017.png
13037.png
13048.png
13049.png
13084.png
13194.png
13220.png
13228.png
13248.png
13274.png
13280.png
13292.png
13325.png
13328.png
13331.png
13335.png
13359.png
13381.png
13390.png
13405.png
13416.png
13457.png
13580.png
13584.png
13586.png
13593.png
13595.png
13600.png
13640.png
13671.png
13767.png
13773.png
13780.png
13806.png
13824.png
13827.png
13839.png
13863.png
13878.png
13923.png
13995.png
14011.png
14046.png
14061.png
14064.png
14081.png
14109.png
14120.png
14123.png
14168.png
14171.png
14178.png
14188.png
14197.png
14215.png
14240.png
14242.png
14243.png
14244.png
14275.png

In [88]:
# zipper - rough
for i in zipper_rough:
  for j in zipper:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/zipper/' + i, './states/zipper/rough/')

10112.png
10371.png
10486.png
10726.png
12704.png
13212.png
13281.png
13290.png
13782.png

In [89]:
# zipper - split_teeth
for i in zipper_splitTeeth:
  for j in zipper:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/zipper/' + i, './states/zipper/split_teeth/')

10073.png
10426.png
10557.png
10605.png
10887.png
11456.png
12374.png
12587.png
13991.png

In [92]:
# zipper - squeezed_teeth
for i in zipper_squeezedTeeth:
  for j in zipper:
    if i>j: continue
    if i==j:
      print(i)
      shutil.move('./states/zipper/' + i, './states/zipper/squeezed_teeth/')

10235.png
10811.png
11430.png
11496.png
11700.png
13187.png
13647.png
13731.png