<a href="https://colab.research.google.com/github/dodamhaee/CV-anomaly-detection-algorithm/blob/main/classify_img.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd drive/MyDrive/Dacon

/content/drive/MyDrive/Dacon

In [4]:
df = pd.read_csv('train_df.csv')

In [5]:
df = df[['class', 'file_name']]
df

           class  file_name
0     transistor  10000.png
1        capsule  10001.png
2     transistor  10002.png
3           wood  10003.png
4         bottle  10004.png
...          ...        ...
4272  transistor  14272.png
4273  transistor  14273.png
4274        grid  14274.png
4275      zipper  14275.png
4276       screw  14276.png

[4277 rows x 2 columns]

In [6]:
df = df.sort_values(by='class')
df

       class  file_name
1273  bottle  11273.png
767   bottle  10767.png
248   bottle  10248.png
3874  bottle  13874.png
772   bottle  10772.png
...      ...        ...
3274  zipper  13274.png
2048  zipper  12048.png
774   zipper  10774.png
3280  zipper  13280.png
4275  zipper  14275.png

[4277 rows x 2 columns]

In [7]:
bottle = df.loc[df['class'] == 'bottle', ['file_name']]
bottle

      file_name
1273  11273.png
767   10767.png
248   10248.png
3874  13874.png
772   10772.png
...         ...
1323  11323.png
1295  11295.png
4179  14179.png
3466  13466.png
1332  11332.png

[241 rows x 1 columns]